######################################################################
PROJ = realspace2spots
OBJ  = realspace2spots.o
LIBS = -l$(LIBXMIPP_INTERFACE) -l$(LIBRECONS) -l$(LIBXMIPP) \
       -l$(LIBRECONS_INTERFACE) 
