######################################################################
PROJ = crystal_aph2img
OBJ  = spots2realspace.o
LIBS = -l$(LIBXMIPP_INTERFACE) -l$(LIBRECONS) -l$(LIBXMIPP) \
       -l$(LIBRECONS_INTERFACE)
