################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
OBJS := 
C++_DEPS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
libraries/reconstruction \
libraries/parallel \
libraries/interface \
libraries/data \
libraries/classification \
libraries/bindings/python \
libraries/bindings/matlab \
libraries/bindings/java \
lib/python2.7/site-packages/numpy/f2py/tests/src/array_from_pyobj \
lib/python2.7/site-packages/numpy/f2py/src \
lib/python2.7/site-packages/numpy/distutils/tests/swig_ext/src \
lib/python2.7/site-packages/numpy/distutils/mingw \
external/tiff-3.9.4/tools \
external/tiff-3.9.4/test \
external/tiff-3.9.4/port \
external/tiff-3.9.4/port/.libs \
external/tiff-3.9.4/libtiff \
external/tiff-3.9.4/libtiff/.libs \
external/tiff-3.9.4/contrib/win_dib \
external/tiff-3.9.4/contrib/tags \
external/tiff-3.9.4/contrib/stream \
external/tiff-3.9.4/contrib/ras \
external/tiff-3.9.4/contrib/pds \
external/tiff-3.9.4/contrib/mfs \
external/tiff-3.9.4/contrib/mac-mpw \
external/tiff-3.9.4/contrib/mac-cw \
external/tiff-3.9.4/contrib/iptcutil \
external/tiff-3.9.4/contrib/dbs/xtiff \
external/tiff-3.9.4/contrib/dbs \
external/tiff-3.9.4/contrib/addtiffo \
external/sqliteExt \
external/sqlite-3.6.23 \
external/sqlite-3.6.23/.libs \
external/python/tk8.5.10/xlib \
external/python/tk8.5.10/win \
external/python/tk8.5.10/unix \
external/python/tk8.5.10/macosx \
external/python/tk8.5.10/generic/ttk \
external/python/tk8.5.10/generic \
external/python/tcl8.5.10/win \
external/python/tcl8.5.10/unix \
external/python/tcl8.5.10/unix/dltest \
external/python/tcl8.5.10/tools \
external/python/tcl8.5.10/macosx \
external/python/tcl8.5.10/libtommath \
external/python/tcl8.5.10/generic \
external/python/tcl8.5.10/compat \
external/python/numpy-1.6.1/numpy/random/mtrand \
external/python/numpy-1.6.1/numpy/numarray \
external/python/numpy-1.6.1/numpy/linalg \
external/python/numpy-1.6.1/numpy/lib/src \
external/python/numpy-1.6.1/numpy/fft \
external/python/numpy-1.6.1/numpy/f2py/tests/src/array_from_pyobj \
external/python/numpy-1.6.1/numpy/f2py/src \
external/python/numpy-1.6.1/numpy/distutils/tests/swig_ext/src \
external/python/numpy-1.6.1/numpy/distutils/mingw \
external/python/numpy-1.6.1/numpy/core/src/umath \
external/python/numpy-1.6.1/numpy/core/src/npymath \
external/python/numpy-1.6.1/numpy/core/src/multiarray \
external/python/numpy-1.6.1/numpy/core/include/numpy/fenv \
external/python/numpy-1.6.1/numpy/core/blasdot \
external/python/numpy-1.6.1/doc/swig/test \
external/python/numpy-1.6.1/doc/pyrex \
external/python/numpy-1.6.1/build/temp.linux-x86_64-2.7/numpy/core/src/npymath \
external/python/numpy-1.6.1/build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/numpy/core/src/npymath \
external/python/numpy-1.6.1/build/temp.linux-i686-2.7/numpy/random/mtrand \
external/python/numpy-1.6.1/build/temp.linux-i686-2.7/numpy/numarray \
external/python/numpy-1.6.1/build/temp.linux-i686-2.7/numpy/linalg \
external/python/numpy-1.6.1/build/temp.linux-i686-2.7/numpy/lib/src \
external/python/numpy-1.6.1/build/temp.linux-i686-2.7/numpy/fft \
external/python/numpy-1.6.1/build/temp.linux-i686-2.7/numpy/core/src/umath \
external/python/numpy-1.6.1/build/temp.linux-i686-2.7/numpy/core/src/npymath \
external/python/numpy-1.6.1/build/temp.linux-i686-2.7/numpy/core/src/multiarray \
external/python/numpy-1.6.1/build/temp.linux-i686-2.7/build/src.linux-i686-2.7/numpy/core/src/umath \
external/python/numpy-1.6.1/build/temp.linux-i686-2.7/build/src.linux-i686-2.7/numpy/core/src \
external/python/numpy-1.6.1/build/temp.linux-i686-2.7/build/src.linux-i686-2.7/numpy/core/src/npymath \
external/python/numpy-1.6.1/build/temp.linux-i686-2.7/build/src.linux-i686-2.7/numpy/core/src/multiarray \
external/python/numpy-1.6.1/build/src.linux-x86_64-2.7/numpy/core/src/umath \
external/python/numpy-1.6.1/build/src.linux-x86_64-2.7/numpy/core/src \
external/python/numpy-1.6.1/build/src.linux-x86_64-2.7/numpy/core/src/npymath \
external/python/numpy-1.6.1/build/src.linux-x86_64-2.7/numpy/core/src/multiarray \
external/python/numpy-1.6.1/build/src.linux-x86_64-2.7/numpy/core/include/numpy \
external/python/numpy-1.6.1/build/src.linux-i686-2.7/numpy/core/src/umath \
external/python/numpy-1.6.1/build/src.linux-i686-2.7/numpy/core/src \
external/python/numpy-1.6.1/build/src.linux-i686-2.7/numpy/core/src/npymath \
external/python/numpy-1.6.1/build/src.linux-i686-2.7/numpy/core/src/multiarray \
external/python/numpy-1.6.1/build/src.linux-i686-2.7/numpy/core/include/numpy \
external/python/mpi4py-1.2.2/src \
external/python/mpi4py-1.2.2/src/MPE \
external/python/mpi4py-1.2.2/demo/wrap-c \
external/python/mpi4py-1.2.2/demo/wrap-boost \
external/python/mpi4py-1.2.2/demo/spawning \
external/python/mpi4py-1.2.2/demo \
external/python/mpi4py-1.2.2/demo/embedding \
external/python/mpi4py-1.2.2/build/temp.linux-x86_64-2.7/src \
external/python/matplotlib-1.1.0/ttconv \
external/python/matplotlib-1.1.0/src \
external/python/matplotlib-1.1.0/lib/matplotlib/tri \
external/python/matplotlib-1.1.0/lib/matplotlib/delaunay \
external/python/matplotlib-1.1.0/build/temp.linux-x86_64-2.7/ttconv \
external/python/matplotlib-1.1.0/build/temp.linux-x86_64-2.7/src \
external/python/matplotlib-1.1.0/build/temp.linux-x86_64-2.7/lib/matplotlib/tri \
external/python/matplotlib-1.1.0/build/temp.linux-x86_64-2.7/lib/matplotlib/delaunay \
external/python/matplotlib-1.1.0/build/temp.linux-x86_64-2.7/agg24/src \
external/python/matplotlib-1.1.0/build/temp.linux-x86_64-2.7/CXX \
external/python/matplotlib-1.1.0/agg24/src/platform/win32 \
external/python/matplotlib-1.1.0/agg24/src/platform/sdl \
external/python/matplotlib-1.1.0/agg24/src/platform/mac \
external/python/matplotlib-1.1.0/agg24/src/platform/X11 \
external/python/matplotlib-1.1.0/agg24/src/platform/BeOS \
external/python/matplotlib-1.1.0/agg24/src/platform/AmigaOS \
external/python/matplotlib-1.1.0/agg24/src/ctrl \
external/python/matplotlib-1.1.0/agg24/src \
external/python/matplotlib-1.1.0/CXX \
external/python/matplotlib-1.1.0/CXX/Python3 \
external/python/matplotlib-1.1.0/CXX/Python2 \
external/python/Python-2.7.2/build/temp.linux-x86_64-2.7/home/jvargas/Linux/Proyectos/xmipp/external/python/Python-2.7.2/Modules \
external/python/Python-2.7.2/build/temp.linux-x86_64-2.7/home/jvargas/Linux/Proyectos/xmipp/external/python/Python-2.7.2/Modules/expat \
external/python/Python-2.7.2/build/temp.linux-x86_64-2.7/home/jvargas/Linux/Proyectos/xmipp/external/python/Python-2.7.2/Modules/cjkcodecs \
external/python/Python-2.7.2/build/temp.linux-x86_64-2.7/home/jvargas/Linux/Proyectos/xmipp/external/python/Python-2.7.2/Modules/_sqlite \
external/python/Python-2.7.2/build/temp.linux-x86_64-2.7/home/jvargas/Linux/Proyectos/xmipp/external/python/Python-2.7.2/Modules/_multiprocessing \
external/python/Python-2.7.2/build/temp.linux-x86_64-2.7/home/jvargas/Linux/Proyectos/xmipp/external/python/Python-2.7.2/Modules/_io \
external/python/Python-2.7.2/build/temp.linux-x86_64-2.7/home/jvargas/Linux/Proyectos/xmipp/external/python/Python-2.7.2/Modules/_ctypes \
external/python/Python-2.7.2/build/temp.linux-x86_64-2.7/home/jvargas/Linux/Proyectos/xmipp/external/python/Python-2.7.2/Modules/_ctypes/libffi/src/x86 \
external/python/Python-2.7.2/build/temp.linux-x86_64-2.7/home/jvargas/Linux/Proyectos/xmipp/external/python/Python-2.7.2/Modules/_ctypes/libffi/src \
external/python/Python-2.7.2/Tools/msi \
external/python/Python-2.7.2/RISCOS \
external/python/Python-2.7.2/RISCOS/Python \
external/python/Python-2.7.2/RISCOS/Modules \
external/python/Python-2.7.2/Python \
external/python/Python-2.7.2/Parser \
external/python/Python-2.7.2/PCbuild \
external/python/Python-2.7.2/PC \
external/python/Python-2.7.2/PC/os2vacpp \
external/python/Python-2.7.2/PC/os2emx \
external/python/Python-2.7.2/PC/example_nt \
external/python/Python-2.7.2/PC/bdist_wininst \
external/python/Python-2.7.2/PC/VS8.0 \
external/python/Python-2.7.2/PC/VS7.1 \
external/python/Python-2.7.2/Objects \
external/python/Python-2.7.2/Modules \
external/python/Python-2.7.2/Modules/zlib \
external/python/Python-2.7.2/Modules/expat \
external/python/Python-2.7.2/Modules/cjkcodecs \
external/python/Python-2.7.2/Modules/_sqlite \
external/python/Python-2.7.2/Modules/_multiprocessing \
external/python/Python-2.7.2/Modules/_io \
external/python/Python-2.7.2/Modules/_ctypes \
external/python/Python-2.7.2/Modules/_ctypes/libffi_osx/x86 \
external/python/Python-2.7.2/Modules/_ctypes/libffi_osx \
external/python/Python-2.7.2/Modules/_ctypes/libffi_osx/powerpc \
external/python/Python-2.7.2/Modules/_ctypes/libffi_msvc \
external/python/Python-2.7.2/Modules/_ctypes/libffi_arm_wince \
external/python/Python-2.7.2/Modules/_ctypes/libffi/testsuite/libffi.special \
external/python/Python-2.7.2/Modules/_ctypes/libffi/testsuite/libffi.call \
external/python/Python-2.7.2/Modules/_ctypes/libffi/src/x86 \
external/python/Python-2.7.2/Modules/_ctypes/libffi/src \
external/python/Python-2.7.2/Modules/_ctypes/libffi/src/sparc \
external/python/Python-2.7.2/Modules/_ctypes/libffi/src/sh64 \
external/python/Python-2.7.2/Modules/_ctypes/libffi/src/sh \
external/python/Python-2.7.2/Modules/_ctypes/libffi/src/s390 \
external/python/Python-2.7.2/Modules/_ctypes/libffi/src/powerpc \
external/python/Python-2.7.2/Modules/_ctypes/libffi/src/pa \
external/python/Python-2.7.2/Modules/_ctypes/libffi/src/moxie \
external/python/Python-2.7.2/Modules/_ctypes/libffi/src/mips \
external/python/Python-2.7.2/Modules/_ctypes/libffi/src/m68k \
external/python/Python-2.7.2/Modules/_ctypes/libffi/src/m32r \
external/python/Python-2.7.2/Modules/_ctypes/libffi/src/ia64 \
external/python/Python-2.7.2/Modules/_ctypes/libffi/src/frv \
external/python/Python-2.7.2/Modules/_ctypes/libffi/src/cris \
external/python/Python-2.7.2/Modules/_ctypes/libffi/src/avr32 \
external/python/Python-2.7.2/Modules/_ctypes/libffi/src/arm \
external/python/Python-2.7.2/Modules/_ctypes/libffi/src/alpha \
external/python/Python-2.7.2/Modules/_ctypes/darwin \
external/python/Python-2.7.2/Misc \
external/python/Python-2.7.2/Mac/Tools \
external/python/Python-2.7.2/Mac/Modules/win \
external/python/Python-2.7.2/Mac/Modules/te \
external/python/Python-2.7.2/Mac/Modules/snd \
external/python/Python-2.7.2/Mac/Modules/scrap \
external/python/Python-2.7.2/Mac/Modules/res \
external/python/Python-2.7.2/Mac/Modules/qt \
external/python/Python-2.7.2/Mac/Modules/qdoffs \
external/python/Python-2.7.2/Mac/Modules/qd \
external/python/Python-2.7.2/Mac/Modules/osa \
external/python/Python-2.7.2/Mac/Modules/mlte \
external/python/Python-2.7.2/Mac/Modules/menu \
external/python/Python-2.7.2/Mac/Modules/list \
external/python/Python-2.7.2/Mac/Modules/launch \
external/python/Python-2.7.2/Mac/Modules/icn \
external/python/Python-2.7.2/Mac/Modules \
external/python/Python-2.7.2/Mac/Modules/ibcarbon \
external/python/Python-2.7.2/Mac/Modules/help \
external/python/Python-2.7.2/Mac/Modules/folder \
external/python/Python-2.7.2/Mac/Modules/fm \
external/python/Python-2.7.2/Mac/Modules/file \
external/python/Python-2.7.2/Mac/Modules/evt \
external/python/Python-2.7.2/Mac/Modules/drag \
external/python/Python-2.7.2/Mac/Modules/dlg \
external/python/Python-2.7.2/Mac/Modules/ctl \
external/python/Python-2.7.2/Mac/Modules/cm \
external/python/Python-2.7.2/Mac/Modules/cg \
external/python/Python-2.7.2/Mac/Modules/cf \
external/python/Python-2.7.2/Mac/Modules/carbonevt \
external/python/Python-2.7.2/Mac/Modules/app \
external/python/Python-2.7.2/Mac/Modules/ah \
external/python/Python-2.7.2/Mac/Modules/ae \
external/python/Python-2.7.2/Doc/includes \
external/python/Python-2.7.2/Demo/pysvr \
external/python/Python-2.7.2/Demo/embed \
external/python/PyCifRW-3.3/lib \
external/python/PyCifRW-3.3/build/temp.linux-x86_64-2.7/lib \
external/jpeg-8c \
external/jpeg-8c/.libs \
external/inria \
external/gtest-1.6.0/fused-src/gtest \
external/fftw-3.3.1/tools \
external/fftw-3.3.1/threads \
external/fftw-3.3.1/threads/.libs \
external/fftw-3.3.1/tests \
external/fftw-3.3.1/support \
external/fftw-3.3.1/simd-support \
external/fftw-3.3.1/simd-support/.libs \
external/fftw-3.3.1/reodft \
external/fftw-3.3.1/reodft/.libs \
external/fftw-3.3.1/rdft \
external/fftw-3.3.1/rdft/simd/sse2 \
external/fftw-3.3.1/rdft/simd/neon \
external/fftw-3.3.1/rdft/simd/common \
external/fftw-3.3.1/rdft/simd/avx \
external/fftw-3.3.1/rdft/simd/altivec \
external/fftw-3.3.1/rdft/scalar \
external/fftw-3.3.1/rdft/scalar/r2r \
external/fftw-3.3.1/rdft/scalar/r2r/.libs \
external/fftw-3.3.1/rdft/scalar/r2cf \
external/fftw-3.3.1/rdft/scalar/r2cf/.libs \
external/fftw-3.3.1/rdft/scalar/r2cb \
external/fftw-3.3.1/rdft/scalar/r2cb/.libs \
external/fftw-3.3.1/rdft/scalar/.libs \
external/fftw-3.3.1/rdft/.libs \
external/fftw-3.3.1/mpi \
external/fftw-3.3.1/libbench2 \
external/fftw-3.3.1/kernel \
external/fftw-3.3.1/kernel/.libs \
external/fftw-3.3.1/dft \
external/fftw-3.3.1/dft/simd/sse2 \
external/fftw-3.3.1/dft/simd/neon \
external/fftw-3.3.1/dft/simd/common \
external/fftw-3.3.1/dft/simd/avx \
external/fftw-3.3.1/dft/simd/altivec \
external/fftw-3.3.1/dft/scalar \
external/fftw-3.3.1/dft/scalar/codelets \
external/fftw-3.3.1/dft/scalar/codelets/.libs \
external/fftw-3.3.1/dft/scalar/.libs \
external/fftw-3.3.1/dft/.libs \
external/fftw-3.3.1/api \
external/fftw-3.3.1/api/.libs \
external/condor \
external/bilib/sources \
external/arpack++-2.3/src \
external/arpack++-2.3/examples/reverse/sym \
external/arpack++-2.3/examples/reverse/nonsym \
external/arpack++-2.3/examples/reverse/complex \
external/arpack++-2.3/examples/product/sym \
external/arpack++-2.3/examples/product/simple \
external/arpack++-2.3/examples/product/nonsym \
external/arpack++-2.3/examples/product/complex \
external/arpack++-2.3/examples/dense/sym \
external/arpack++-2.3/examples/dense/nonsym \
external/arpack++-2.3/examples/dense/complex \
external/arpack++-2.3/examples/band/sym \
external/arpack++-2.3/examples/band/nonsym \
external/arpack++-2.3/examples/band/complex \
build/config.tests \
applications/tests/test_transformation \
applications/tests/test_symmetries \
applications/tests/test_sampling \
applications/tests/test_polynomials \
applications/tests/test_polar \
applications/tests/test_multidim \
applications/tests/test_metadata \
applications/tests/test_matrix \
applications/tests/test_image_generic \
applications/tests/test_image \
applications/tests/test_geometry \
applications/tests/test_funcs \
applications/tests/test_fringe_processing \
applications/tests/test_filters \
applications/tests/test_fftw \
applications/tests/test_euler \
applications/programs/xray_psf_create \
applications/programs/xray_project \
applications/programs/xray_import \
applications/programs/volume_to_web \
applications/programs/volume_to_pseudoatoms \
applications/programs/volume_segment \
applications/programs/volume_reslice \
applications/programs/volume_from_pdb \
applications/programs/volume_find_symmetry \
applications/programs/volume_enhance_contrast \
applications/programs/volume_correct_bfactor \
applications/programs/volume_center \
applications/programs/volume_align \
applications/programs/transform_window \
applications/programs/transform_threshold \
applications/programs/transform_symmetrize \
applications/programs/transform_range_adjust \
applications/programs/transform_normalize \
applications/programs/transform_morphology \
applications/programs/transform_mirror \
applications/programs/transform_mask \
applications/programs/transform_geometry \
applications/programs/transform_filter \
applications/programs/transform_downsample \
applications/programs/transform_center_image \
applications/programs/transform_adjust_volume_grey_levels \
applications/programs/transform_add_noise \
applications/programs/tomo_remove_fluctuations \
applications/programs/tomo_project \
applications/programs/tomo_extract_subvolume \
applications/programs/tomo_detect_missing_wedge \
applications/programs/tomo_align_tilt_series \
applications/programs/tomo_align_refinement \
applications/programs/tomo_align_dual_tilt_series \
applications/programs/template_threads \
applications/programs/template_mpi \
applications/programs/resolution_ssnr \
applications/programs/resolution_ibw \
applications/programs/resolution_fsc \
applications/programs/reconstruct_wbp \
applications/programs/reconstruct_fourier \
applications/programs/reconstruct_art_xray \
applications/programs/reconstruct_art_pseudo \
applications/programs/reconstruct_art \
applications/programs/randomize_angles \
applications/programs/phantom_transform \
applications/programs/phantom_simulate_microscope \
applications/programs/phantom_project \
applications/programs/phantom_create \
applications/programs/pdb_nma_deform \
applications/programs/nma_alignment \
applications/programs/mrc_create_metadata \
applications/programs/mpi_xray_project \
applications/programs/mpi_write_test \
applications/programs/mpi_transform_symmetrize \
applications/programs/mpi_transform_normalize \
applications/programs/mpi_transform_mask \
applications/programs/mpi_transform_geometry \
applications/programs/mpi_transform_filter \
applications/programs/mpi_tomo_extract_subvolume \
applications/programs/mpi_run \
applications/programs/mpi_reconstruct_wbp \
applications/programs/mpi_reconstruct_fourier \
applications/programs/mpi_reconstruct_art \
applications/programs/mpi_performance_test \
applications/programs/mpi_nma_alignment \
applications/programs/mpi_mlf_tomo \
applications/programs/mpi_mlf_refine3d \
applications/programs/mpi_mlf_align2d \
applications/programs/mpi_ml_tomo \
applications/programs/mpi_ml_refine3d \
applications/programs/mpi_ml_align3d \
applications/programs/mpi_ml_align2d \
applications/programs/mpi_image_sort \
applications/programs/mpi_image_rotational_pca \
applications/programs/mpi_image_operate \
applications/programs/mpi_ctf_sort_psds \
applications/programs/mpi_ctf_correct_idr \
applications/programs/mpi_create_projection_library \
applications/programs/mpi_classify_FTTRI \
applications/programs/mpi_classify_CL3D \
applications/programs/mpi_classify_CL2D_core_analysis \
applications/programs/mpi_classify_CL2D \
applications/programs/mpi_angular_projection_matching \
applications/programs/mpi_angular_project_library \
applications/programs/mpi_angular_gcar_commonlines \
applications/programs/mpi_angular_continuous_assign \
applications/programs/mpi_angular_class_average \
applications/programs/mlf_tomo \
applications/programs/mlf_refine3d \
applications/programs/mlf_align2d \
applications/programs/ml_tomo \
applications/programs/ml_refine3d \
applications/programs/ml_align2d \
applications/programs/micrograph_scissor \
applications/programs/micrograph_automatic_picking \
applications/programs/metadata_utilities \
applications/programs/metadata_split \
applications/programs/metadata_import \
applications/programs/metadata_histogram \
applications/programs/metadata_convert_to_spider \
applications/programs/metadata_convert_22_emx \
applications/programs/image_vectorize \
applications/programs/image_statistics \
applications/programs/image_sort_by_statistics \
applications/programs/image_separate_objects \
applications/programs/image_rotational_spectra \
applications/programs/image_rotational_pca \
applications/programs/image_operate \
applications/programs/image_histogram \
applications/programs/image_header \
applications/programs/image_find_center \
applications/programs/image_convert \
applications/programs/image_align_tilt_pairs \
applications/programs/image_align \
applications/programs/fourier_filter \
applications/programs/ctf_sort_psds \
applications/programs/ctf_show \
applications/programs/ctf_phase_flip \
applications/programs/ctf_group \
applications/programs/ctf_estimate_from_psd \
applications/programs/ctf_estimate_from_micrograph \
applications/programs/ctf_enhance_psd \
applications/programs/ctf_create_ctfdat \
applications/programs/ctf_correct_wiener3d \
applications/programs/ctf_correct_idr \
applications/programs/classify_kerdensom \
applications/programs/classify_evaluate_classes \
applications/programs/classify_compare_classes \
applications/programs/classify_analyze_cluster \
applications/programs/angular_rotate \
applications/programs/angular_projection_matching \
applications/programs/angular_project_library \
applications/programs/angular_neighbourhood \
applications/programs/angular_gcar \
applications/programs/angular_distribution_show \
applications/programs/angular_distance \
applications/programs/angular_discrete_assign \
applications/programs/angular_continuous_assign \
applications/programs/angular_commonline \

