######################################################################
PROJ = idr_art
OBJ  = idr_art.o
LIBS = -l$(LIBXMIPP) -l$(LIBRECONS) -l$(LIBXMIPP_INTERFACE) \
       -l$(LIBRECONS_VTK) -l$(LIBXMIPP_INTERFACE_VTK) $(LIBVTK)
