package xmipp; 
public class MDLabel {
   public static final int MDL_UNDEFINED = -1;
   public static final int MDL_FIRST_LABEL = 0;  ///< The label MDL_OBJID is special and should not be used
   public static final int MDL_OBJID = MDL_FIRST_LABEL; ///< object id (int); NOTE: This label is special and shouldn't be used
   public static final int MDL_ANGLEPSI2 = 1;  ///< Psi angle of an image (double = 1; degrees)
   public static final int MDL_ANGLEPSI = 2;  ///< Psi angle of an image (double = 2; degrees)
   public static final int MDL_ANGLEROT2 = 3;  ///< Rotation angle of an image (double = 3; degrees)
   public static final int MDL_ANGLEROT = 4;  ///< Rotation angle of an image (double = 4; degrees)
   public static final int MDL_ANGLETILT2 = 5;  ///< Tilting angle of an image (double = 5; degrees)
   public static final int MDL_ANGLETILT = 6;  ///< Tilting angle of an image (double = 6; degrees)
   public static final int MDL_ASSOCIATED_IMAGE1 = 7;  ///< Image associated to this object (std::string)
   public static final int MDL_ASSOCIATED_IMAGE2 = 8;  ///< Image associated to this object (std::string)
   public static final int MDL_ASSOCIATED_IMAGE3 = 9;  ///< Image associated to this object (std::string)
   public static final int MDL_ASSOCIATED_IMAGE4 = 10;  ///< Image associated to this object (std::string)
   public static final int MDL_ASSOCIATED_IMAGE5 = 11;  ///< Image associated to this object (std::string)
   public static final int MDL_AVG = 12;  ///< average value (double)
   public static final int MDL_AZIMUTALANGLE = 13;  ///< ctf definition azimutal angle
   public static final int MDL_BGMEAN = 14;  ///< Mean background value for an image
   public static final int MDL_BLOCK = 15;  ///< Current block number (for incremental EM)
   public static final int MDL_CELLX = 16;  ///< Cell location for crystals
   public static final int MDL_CELLY = 17;  ///< Cell location for crystals
   public static final int MDL_COMMENT = 18;  ///< A comment for this object /*** NOTE THIS IS A SPECIAL CASE AND SO IS TREATED ***/
   public static final int MDL_COST = 19;  ///< Cost for the image (double)
   public static final int MDL_COUNT = 20;  ///< Number of elements of a type (int) [this is a genereic type do not use to transfer information to another program]
   public static final int MDL_CTFINPUTPARAMS = 21;  ///< Parameters file for the CTF Model (std::string)
   public static final int MDL_CTFMODEL = 22;  ///< Name for the CTF Model (std::string)
   public static final int MDL_CTFMODEL2 = 23;  ///< Name for another CTF model (std::string)
   public static final int MDL_CTF_SAMPLING_RATE = 24;  ///< Sampling rate
   public static final int MDL_CTF_SAMPLING_RATE_Z = 25;  ///< Sampling rate in Z direction
   public static final int MDL_CTF_VOLTAGE = 26;  ///< Microscope voltage (kV)
   public static final int MDL_CTF_DEFOCUSA = 27;  ///< aver (Angage defocusstroms)
   public static final int MDL_CTF_DEFOCUSU = 28;  ///< Defocus U (Angstroms)
   public static final int MDL_CTF_DEFOCUSV = 29;  ///< Defocus V (Angstroms)
   public static final int MDL_CTF_DEFOCUS_ANGLE = 30;  ///< Defocus angle (degrees)
   public static final int MDL_CTF_CS = 31;  ///< Spherical aberration
   public static final int MDL_CTF_CA = 32;  ///< Chromatic aberration
   public static final int MDL_CTF_ENERGY_LOSS = 33;  ///< Energy loss
   public static final int MDL_CTF_LENS_STABILITY = 34;  ///< Lens stability
   public static final int MDL_CTF_CONVERGENCE_CONE = 35;  ///< Convergence cone
   public static final int MDL_CTF_LONGITUDINAL_DISPLACEMENT = 36;  ///< Longitudinal displacement
   public static final int MDL_CTF_TRANSVERSAL_DISPLACEMENT = 37;  ///< Transversal displacemente
   public static final int MDL_CTF_Q0 = 38;  ///< Inelastic absorption
   public static final int MDL_CTF_K = 39;  ///< CTF gain
   public static final int MDL_CTFBG_GAUSSIAN_K = 40;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN_SIGMAU = 41;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN_SIGMAV = 42;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN_CU = 43;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN_CV = 44;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN_ANGLE = 45;  ///< CTF Background parameter
   public static final int MDL_CTFBG_SQRT_K = 46;  ///< CTF Background parameter
   public static final int MDL_CTFBG_SQRT_U = 47;  ///< CTF Background parameter
   public static final int MDL_CTFBG_SQRT_V = 48;  ///< CTF Background parameter
   public static final int MDL_CTFBG_SQRT_ANGLE = 49;  ///< CTF Background parameter
   public static final int MDL_CTFBG_BASELINE = 50;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN2_K = 51;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN2_SIGMAU = 52;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN2_SIGMAV = 53;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN2_CU = 54;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN2_CV = 55;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN2_ANGLE = 56;  ///< CTF Background parameter
   public static final int MDL_CTF_CRITERION_PSDCORRELATION90 = 57;  ///< PSD correlation at 90 degrees
   public static final int MDL_CTF_CRITERION_FIRSTZERORATIO = 58;  ///< First zero ratio
   public static final int MDL_CTF_CRITERION_FIRSTZEROAVG = 59;  ///< First zero average (in Angstroms)
   public static final int MDL_CTF_CRITERION_FIRSTZERODISAGREEMENT = 60;  ///< First zero disagreement with second model (in Angstroms)
   public static final int MDL_CTF_CRITERION_DAMPING = 61;  ///< Minimum damping at border
   public static final int MDL_CTF_CRITERION_PSDRADIALINTEGRAL = 62;  ///< Integral of the radial PSD
   public static final int MDL_CTF_CRITERION_FITTINGSCORE = 63;  ///< Score of the fitting
   public static final int MDL_CTF_CRITERION_FITTINGCORR13 = 64;  ///< Correlation between the 1st and 3rd ring of the CTF
   public static final int MDL_CTF_CRITERION_PSDVARIANCE = 65;  ///< PSD variance
   public static final int MDL_CTF_CRITERION_PSDPCA1VARIANCE = 66;  ///< Variance in the first principal component of the PSDs
   public static final int MDL_CTF_CRITERION_PSDPCARUNSTEST = 67;  ///< Runs test on the projection of the PSD on the first principal component
   public static final int MDL_CTF_XRAY_DIMENSIONS = 68;  // Size in pixels of the 3D PSF to be created (Xdim = 68;  Ydim = 68;  Zdim)
   public static final int MDL_CTF_XRAY_LAMBDA = 69;  /// X-ray wavelength (nm)
   public static final int MDL_CTF_XRAY_LENS_TYPE = 70;  ///Algorithm used to generate Xray PSF
   public static final int MDL_CTF_XRAY_MAGNIFICATION = 71;  /// Magnification of the X-ray microscope
   public static final int MDL_CTF_XRAY_OUTER_ZONE_WIDTH = 72;  /// Outermost zone width of the X-ray Fresnel lens (nm)
   public static final int MDL_CTF_XRAY_ZONES_NUMBER = 73;  // Number of zones of the X-ray Fresnel lens
   public static final int MDL_DATATYPE = 74;  ///< if read from file original image datatype = 74;  this is an struct defined in image
   public static final int MDL_DEFGROUP = 75;  ///< Defocus group
   public static final int MDL_DM3_IDTAG = 76; 
   public static final int MDL_DM3_NODEID = 77; 
   public static final int MDL_DM3_NUMBER_TYPE = 78; 
   public static final int MDL_DM3_PARENTID = 79; 
   public static final int MDL_DM3_TAGCLASS = 80; 
   public static final int MDL_DM3_TAGNAME = 81; 
   public static final int MDL_DM3_SIZE = 82; 
   public static final int MDL_DM3_VALUE = 83; 
   public static final int MDL_ENABLED = 84;  ///< Is this image enabled? (int [-1 or 1])
   public static final int MDL_FLIP = 85;  ///< Flip the image? (bool)
   public static final int MDL_IMAGE_CLASS_COUNT = 86;  ///< Number of images assigned to the same class as this image
   public static final int MDL_IMAGE_CLASS_GROUP = 87;  ///< Name of the class group for this image (metadata with all the images assigned to that class)
   public static final int MDL_IMAGE_CLASS = 88;  ///< Name of the class representative for this image
   public static final int MDL_IMAGE = 89;  ///< Name of an image (std::string)
   public static final int MDL_IMAGE_ORIGINAL = 90;  ///< Name of an image from which MDL_IMAGE is coming from
   public static final int MDL_IMAGE_TILTED = 91;  ///< Name of the tilted images associated to MDL_IMAGE
   public static final int MDL_IMGMD = 92;  ///< Name of Metadata file for all images (string)
   public static final int MDL_INTSCALE = 93;  ///< Intensity scale for an image
   public static final int MDL_ITER = 94;  ///< Current iteration number (int)
   public static final int MDL_K = 95;  ///< //ctf definition K
   public static final int MDL_KSTEST = 96;  ///<KS-test statistics
   public static final int MDL_LL = 97;  ///< contribution of an image to log-likelihood value
   public static final int MDL_MASK = 98;  ///< Name of a mask associated to image
   public static final int MDL_MAXCC = 99;  ///< Cross-correlation for the image (double)
   public static final int MDL_MAX = 100;  ///<maximum value (double)
   public static final int MDL_MICROGRAPH = 101;  ///< Name of a micrograph (std::string)
   public static final int MDL_MICROGRAPH_TILTED = 102;  ///< Name of the corresponding tilted micrograph (std::string)
   public static final int MDL_MIN = 103;  ///<minimum value (double)
   public static final int MDL_MIRRORFRAC = 104;  ///< Mirror fraction for a Maximum Likelihood model
   public static final int MDL_MISSINGREGION_NR = 105;  ///< Number of missing region in subtomogram
   public static final int MDL_MISSINGREGION_TYPE = 106;  ///< Type of missing region in subtomogram
   public static final int MDL_MISSINGREGION_THY0 = 107;  ///< Initial tilt angle in Y for missing region in subtomogram
   public static final int MDL_MISSINGREGION_THYF = 108;  ///< Final tilt angle in Y for missing region in subtomogram
   public static final int MDL_MISSINGREGION_THX0 = 109;  ///< Initial tilt angle in X for missing region in subtomogram
   public static final int MDL_MISSINGREGION_THXF = 110;  ///< Final tilt angle in X for missing region in subtomogram
   public static final int MDL_MODELFRAC = 111;  ///< Model fraction (alpha_k) for a Maximum Likelihood model
   public static final int MDL_NMA = 112;  ///< Normal mode displacements (vector double)
   public static final int MDL_NOISE_ANGLES = 113;  ///< Noise description for projected angles
   public static final int MDL_NOISE_PARTICLE_COORD = 114;  ///< Noise description for particle's center coordenates (when projecting)
   public static final int MDL_NOISE_PIXEL_LEVEL = 115;  ///< Noise description for pixels' gray level (when projecting)
   public static final int MDL_ORDER = 116;  /// auxiliary label to be used as an index
   public static final int MDL_ORIGINX = 117;  ///< Origin for the image in the X axis (double)
   public static final int MDL_ORIGINY = 118;  ///< Origin for the image in the Y axis (double)
   public static final int MDL_ORIGINZ = 119;  ///< Origin for the image in the Z axis (double)
   public static final int MDL_PMAX = 120;  ///< Maximum value of normalized probability function (now called "Pmax/sumP") (double)
   public static final int MDL_PRJ_DIMENSIONS = 121;  // X = 121; Y dimensions for the generated projections
   public static final int MDL_PRJ_TILT_RANGE = 122;  // Vector with the initial and final tilt angle values = 122;  and step size
   public static final int MDL_PRJ_VOL = 123;         // Volume file name to generate projections from
   public static final int MDL_PSD = 124;  ///< A Power Spectrum Density file name (std::string)
   public static final int MDL_RANDOMSEED = 125;  ///< Seed for random number generator
   public static final int MDL_REF3D = 126;  ///< 3D Class to which the image belongs (int)
   public static final int MDL_REF = 127;  ///< Class to which the image belongs (int)
   public static final int MDL_REFMD = 128;  ///< Name of Metadata file for all references(string)
   public static final int MDL_RESOLUTION_DPR = 129;  ///<differential phase residual (double)
   public static final int MDL_RESOLUTION_ERRORL2 = 130;  ///<Error in l2 (double)
   public static final int MDL_RESOLUTION_FRC = 131;  ///<Fourier shell correlation (double)
   public static final int MDL_RESOLUTION_FRCRANDOMNOISE = 132;  ///<Fourier shell correlation noise (double)
   public static final int MDL_RESOLUTION_FREQ = 133;  ///<Frequency in 1/A (double)
   public static final int MDL_RESOLUTION_FREQREAL = 134;  ///< Frequency in A (double)
   public static final int MDL_SAMPLINGRATE = 135;  ///< sampling rate in A/pixel (double)
   public static final int MDL_SAMPLINGRATEX = 136;  ///< sampling rate in A/pixel (double)
   public static final int MDL_SAMPLINGRATEY = 137;  ///< sampling rate in A/pixel (double)
   public static final int MDL_SAMPLINGRATEZ = 138;  ///< sampling rate in A/pixel (double)
   public static final int MDL_SCALE = 139;  ///< scaling factor for an image or volume (double)
   public static final int MDL_SELFILE = 140;  ///< Name of an image (std::string)
   public static final int MDL_SERIE = 141;  ///< A collection of micrographs = 141;  e.g. a tilt serie (std::string)
   public static final int MDL_SHIFTX = 142;  ///< Shift for the image in the X axis (double)
   public static final int MDL_SHIFTY = 143;  ///< Shift for the image in the Y axis (double)
   public static final int MDL_SHIFTZ = 144;  ///< Shift for the image in the Z axis (double)
   public static final int MDL_SHIFT_CRYSTALX = 145;  ///< Shift for the image in the X axis (double) for crystals
   public static final int MDL_SHIFT_CRYSTALY = 146;  ///< Shift for the image in the Y axis (double) for crystals
   public static final int MDL_SHIFT_CRYSTALZ = 147;  ///< Shift for the image in the Z axis (double) for crystals
   public static final int MDL_SIGMANOISE = 148;  ///< Standard deviation of the noise in ML model
   public static final int MDL_SIGMAOFFSET = 149;  ///< Standard deviation of the offsets in ML model
   public static final int MDL_SIGNALCHANGE = 150;  ///< Signal change for an image
   public static final int MDL_SPHERICALABERRATION = 151;  ///<ctf definition azimutal angle
   public static final int MDL_STDDEV = 152;  ///<stdandard deviation value (double)
   public static final int MDL_SUM = 153;  ///< Sum of elements of a given type (double) [this is a genereic type do not use to transfer information to another program]
   public static final int MDL_SUMWEIGHT = 154;  ///< Sum of all weights in ML model
   public static final int MDL_SYMNO = 155;  ///< Symmetry number for a projection (used in ART)
   public static final int MDL_TRANSFORMATIONMTRIX = 156;  ///< transformation matrix(vector double)
   public static final int MDL_VOLTAGE = 157;  ///< microscope voltage (double)
   public static final int MDL_WEIGHT = 158;  ///< Weight assigned to the image (double)
   public static final int MDL_WROBUST = 159;  ///< Weight of t-student distribution in robust Maximum likelihood
   public static final int MDL_XINT = 160;  ///< X component (int)
   public static final int MDL_XINTTILT = 161;  ///< X component in tilted micrograph (int)
   public static final int MDL_X = 162;  ///< X component (double)
   public static final int MDL_YINT = 163;  ///< Y component (int)
   public static final int MDL_YINTTILT = 164;  ///< Y component in tilted micrograph (int)
   public static final int MDL_Y = 165;  ///< Y component (double)
   public static final int MDL_ZINT = 166;  ///< Z component (int)
   public static final int MDL_Z = 167;  ///< Z component (double)
   public static final int MDL_ZSCORE = 168;  ///< Z Score (double)
   public static final int MDL_LAST_LABEL = 169;                       // **** NOTE ****: Do keep this label always at the end
}
