#!/bin/sh

#Some flags variables

DO_UNTAR=true
DO_SQLITE=true
DO_TCLTK=true
DO_PYTHON=true
DO_FFTW=true
DO_TIFF=true
DO_ARPACK=false
DO_CLEAN=true

DO_STATIC=false
CPU=$@

#Some path variables
XMIPP_HOME=$PWD
EXT_PATH=$XMIPP_HOME/external
BUILD_PATH=$XMIPP_HOME/build

#External libraries versions
VSQLITE=sqlite-3.6.23
VTCLTK=8.5.10
VPYTHON=Python-2.7.2
VFFTW=fftw-3.2.2
VTIFF=tiff-3.9.4
VARPACK=arpack++-2.3
VNUMPY=numpy-1.6.1
VMATLIBPLOT=matplotlib-1.0.1

# Some other vars

GREEN="\033[32m"
RED="\033[31m"
ENDC="\033[0m"

#################### PARSING PARAMETERS ###########################

#for p in $@; do
#   echo "param: $p" 
#done
#exit 1


#################### DECOMPRESSING EXTERNAL LIBRARIES ###########################
if $DO_UNTAR; then  
  dirs=". python"
  echo
  echo -e "$GREEN*** Decompressing external libraries ...$ENDC"
  #Enter to external dir
  echo "--> cd $EXT_PATH"
  cd $EXT_PATH
  for d in $dirs; do
    echo "--> cd $d"
    cd $d 
    for file in $(ls *.tgz); do
      echo "--> tar -xvzf $file > /dev/null"
      tar -xvzf $file > /dev/null
    done
    echo "--> cd -"
    cd - > /dev/null
  done
fi

if ! $DO_STATIC; then
  echo "--> Enabling shared libraries..."
   CONFIGFLAGS=--enable-shared
fi

compile_library()
{
   LIB=$1
   PREFIX_PATH=$2
   SUFFIX_PATH=$3
   FLAGS=$4
   LIBS_PATH=$5
   _PATH=$EXT_PATH/$PREFIX_PATH/$LIB/$SUFFIX_PATH
  echo
  echo -e "$GREEN*** Compiling $LIB ...$ENDC"
  echo "--> cd $_PATH"
  cd $_PATH

  if $DO_CLEAN; then
    echo "make distclean > /dev/null 2>&1"
    make distclean > /dev/null 2>&1
  fi

  echo "--> ./configure $CONFIGFLAGS $FLAGS >$BUILD_PATH/${LIB}_configure.log 2>&1"
  ./configure $CONFIGFLAGS $FLAGS >$BUILD_PATH/${LIB}_configure.log 2>&1
  echo "--> make $CPU >$BUILD_PATH/${LIB}_make.log 2>&1"
  make $CPU >$BUILD_PATH/${LIB}_make.log 2>&1

}

compile_pymodule()
{
   MOD=$1
   _PATH=$EXT_PATH/python/$MOD
   _PYTHON=$EXT_PATH/python/$VPYTHON/python
   cd $_PATH
   $_PYTHON setup.py install --prefix $XMIPP_HOME >$BUILD_PATH/${MOD}_setup_install.log 2>&1 
   
}

#This function should be called from XMIPP_HOME
install_libs()
{
  cd $XMIPP_HOME
  LIBPATH=../external/$1; shift
  COMMON=$1; shift
  SUFFIXES=$@
  for suffix in $SUFFIXES; do
     LIBNAME=$COMMON$suffix
     echo "--> ln -sf $LIBPATH/$LIBNAME lib/$LIBNAME"
     ln -sf $LIBPATH/$LIBNAME lib/$LIBNAME  
  done
}

install_bin()
{
  cd $XMIPP_HOME
  BINPATH=../external/$1
  LINKNAME=bin/$2
  echo "--> ln -sf $BINPATH $LINKNAME"
  ln -sf $BINPATH $LINKNAME
}

#################### SQLITE ###########################
if $DO_SQLITE; then
  compile_library $VSQLITE "." "." "CPPFLAGS=-w CFLAGS=-DSQLITE_ENABLE_UPDATE_DELETE_LIMIT=1" ".libs"
  install_bin $VSQLITE/sqlite3 xmipp_sqlite3
  install_libs $VSQLITE/.libs libsqlite3. a la so so.0
fi

#################### TCL/TK ###########################
if $DO_TCLTK; then
  compile_library tcl$VTCKTK python unix ""
  compile_library tk$VTCKTK python unix ""
fi

#################### PYTHON ###########################
if $DO_PYTHON; then
  compile_library $VPYTHON python "." ""
  install_bin python/$VPYTHON/python xmipp_python
  install_libs python/$VPYTHON libpython2.7. a so so.1.0
  compile_pymodule $VNUMPY
  compile_pymodule $VMATLIBPLOT
fi

#################### FFTW ###########################
if $DO_FFTW; then
  compile_library $VFFTW "." "." "--enable-threads"
  install_libs $VFFTW/.libs libfftw3. a la so so.3
  install_libs $VFFTW/threads/.libs libfftw3_threads. a la so so.3
fi

#################### TIFF ###########################
if $DO_TIFF; then
  compile_library $VTIFF "." "." "CPPFLAGS=-w"
  install_libs $VTIFF/libtiff/.libs libtiff. a la so so.3
fi

#################### ARPACK ###########################
if $DO_ARPACK; then
  compile_library $VARPACK "." "." ""
  install_libs $VARPACK/src/.libs libarpack++. a la so
fi
