/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xmipp_Filename */

#ifndef _Included_xmipp_jni_PickingClassifier
#define _Included_xmipp_jni_PickingClassifier
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     xmipp_PickingClassifier
 * Method:    autopick
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT void JNICALL Java_xmipp_jni_PickingClassifier_autopick
  (JNIEnv *, jclass, jstring);


JNIEXPORT void JNICALL Java_xmipp_jni_PickingClassifier_correct
  (JNIEnv *, jclass, jstring);

JNIEXPORT void JNICALL Java_xmipp_jni_PickingClassifier_train
  (JNIEnv *, jclass, jobjectArray);


#ifdef __cplusplus
}
#endif
#endif
