/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xmipp_Filename */

#ifndef _Included_xmipp_jni_PickingClassifier
#define _Included_xmipp_jni_PickingClassifier
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     xmipp_Filename
 * Method:    hasStackExtension
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_xmipp_jni_PickingClassifier_autopick
  (JNIEnv *, jclass, jstring);

/*
 * Class:     xmipp_Filename
 * Method:    hasVolumeExtension
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_xmipp_jni_PickingClassifier_correct
  (JNIEnv *, jclass, jstring);


#ifdef __cplusplus
}
#endif
#endif
