#!/bin/sh

VERSION=1.2
NEW_NAME=xmipp_create_random_phantom

# Warn user
echo "** Warning! This program name is deprecated as of Xmipp version" $VERSION
echo "** Please use" $NEW_NAME "instead"
echo "** Continuing execution..."

# Call real program
$NEW_NAME "$@"
