/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameTextFile.java
 *
 * Created on 12-dic-2010, 0:46:53
 */
package xmipp.viewer.windows;

import ij.IJ;

import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import javax.swing.JDialog;
import javax.swing.JFrame;

import xmipp.utils.XmippDialog;

/**
 *
 * @author Juanjo Vega
 */
public class TextfileJFrame extends JFrame {

    /** Creates new form JFrameTextFile */
    public TextfileJFrame(String filename) {
    	super(filename);
    	setPreferredSize(new Dimension(600, 400));
    	setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initComponents();
        loadFile(filename);
        pack();
    }

    private void loadFile(String filename) {
        File file = new File(filename);

        try {
            BufferedReader inputStream = new BufferedReader(new FileReader(file));

            String line;
            StringBuilder text = new StringBuilder();
            while ((line = inputStream.readLine()) != null) {
                text.append(line);
                text.append("\n");
            }

            jepEditorPane.setText(text.toString());
        } catch (FileNotFoundException fnfex) {
            IJ.error("File not found: " + fnfex.getMessage());
        } catch (Exception ex) {
            ex.printStackTrace(System.err);
            IJ.error(ex.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jspEditor = new javax.swing.JScrollPane();
        jepEditorPane = new javax.swing.JEditorPane();
        jepEditorPane.setEditable(false);
        //jepEditorPane.setPreferredSize(new java.awt.Dimension(300, 300));
        jspEditor.setViewportView(jepEditorPane);
        getContentPane().add(jspEditor, java.awt.BorderLayout.CENTER);
        
    }// </editor-fold>//GEN-END:initComponents

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jbOkActionPerformed

    private javax.swing.JEditorPane jepEditorPane;
    private javax.swing.JPanel jpButtons;
    private javax.swing.JScrollPane jspEditor;
    // End of variables declaration//GEN-END:variables
}
