#!/usr/bin/env python
import os,glob,sys

if len(sys.argv) < 2:
   print 'Usage: selfile_create "pattern" > metadataFile'
   sys.exit()

scriptdir=os.path.split(os.path.dirname(os.popen('which xmipp_protocols','r').read()))[0]+'/lib'
sys.path.append(scriptdir) # add default search path
import XmippData,os,glob,sys

id=mD.addObject();

for file in glob.glob(sys.argv[1]):
    mD.addObject();
    mD.setImage(file)
    mD.setEnabled("1")
mD.write("std::cout")
