#!/usr/bin/env xmipp_python
#------------------------------------------------------------------------------------------------
# Wrapper for relion 1.2
#
#   Author: Roberto Marabini
#

from os.path import join, exists
from os import remove, rename
from protlib_base import protocolMain
from config_protocols import protDict
from xmipp import *
from xmipp import MetaDataInfo
from protlib_utils import runShowJ, getListFromVector, getListFromRangeString, \
                          runJob, runChimera, which, runChimeraClient
from protlib_parser import ProtocolParser
from protlib_xmipp import redStr, cyanStr
from protlib_gui_ext import showWarning, showTable, showError
from protlib_filesystem import xmippExists, findAcquisitionInfo, moveFile, \
                               replaceBasenameExt
from protocol_ml2d import lastIteration
from protlib_filesystem import createLink
from protlib_relion import *


class ProtRelionClassifier(ProtRelionBase):
    
    def __init__(self, scriptname, project):
        ProtRelionBase.__init__(self, protDict.relion_classify.name, scriptname, project)
        self.Import = 'from protocol_relion_classify import *'
        
        if self.DoContinue:
            #if optimizer has not been properly selected this will 
            #fail, let us go ahead and handle the situation in verify
            try:
                self.inputProperty('MaskRadiusA')
                self.inputProperty('NumberOfClasses')
                self.inputProperty('RegularisationParamT')
                self.inputProperty('Ref3D')

            except:
                print "Can not access the parameters from the original relion run"
        
    def _summary(self):
        lastIteration = self.lastIter()
        lines = ['Performed <%d/%d> iterations ' % (lastIteration, self.NumberOfIterations)]
        lines.append('Number of classes = <%d>' % self.NumberOfClasses)
        
        return lines

    def _summaryContinue(self):
        lastIteration = self.lastIter()
        firstIteration = getIteration(self.optimiserFileName)
        lines = ['Continuation from run: <%s>, iter: <%d>' % (self.PrevRunName, firstIteration)]
        if (lastIteration - firstIteration) < 0 :
            performedIteration = 0
        else:
            performedIteration = lastIteration - firstIteration
        lines.append('Performed <%d> iterations (number estimated from the files in working directory)' % performedIteration) 
        lines.append('Input fileName = <%s>'%self.optimiserFileName)
        return lines
    
    def _validateContinue(self):
        lastIterationPrecRun = self.PrevRun.lastIter()
        errors = []
        if '3D/RelionClass' not in self.optimiserFileName:
            message = 'File <%s> has not been generated by a relion classify protocol'%self.optimiserFileName
            if '3D/RelionRef' in self.optimiserFileName:
                message += " but by relion refine"
            errors.append(message)
        return errors 
    
    def _insertSteps(self):
        args = {'--iter': self.NumberOfIterations,
                '--tau2_fudge': self.RegularisationParamT,
                '--flatten_solvent': '',
                #'--zero_mask': '',# set it to true using additional argument
                '--norm': '',
                '--scale': '',
                '--o': '%s/relion' % self.ExtraDir
                }
        if getattr(self, 'ReferenceMask', '').strip():
            args['--solvent_mask'] = self.ReferenceMask.strip()
            
        if getattr(self, 'SolventMask', '').strip():
            args['--solvent_mask2'] = self.SolventMask.strip()
            
        args.update({'--i': self.ImgStar,
                     '--particle_diameter': self.MaskRadiusA * 2.0,
                     '--angpix': self.SamplingRate,
                     '--ref': self.Ref3D,
                     '--oversampling': '1'
                     })
        
        if not self.IsMapAbsoluteGreyScale:
            args[' --firstiter_cc'] = '' 
            
        if self.InitialLowPassFilterA > 0:
            args['--ini_high'] = self.InitialLowPassFilterA
            
        # CTF stuff
        if self.DoCTFCorrection:
            args['--ctf'] = ''
        
        if self.HasReferenceCTFCorrected:
            args['--ctf_corrected_ref'] = ''
            
        if self.HaveDataPhaseFlipped:
            args['--ctf_phase_flipped'] = ''
            
        if self.IgnoreCTFUntilFirstPeak:
            args['--ctf_intact_first_peak'] = ''
            
        MaskZero = getattr(self, 'MaskZero', '')
        if MaskZero.startswith('Yes'):
            args['--zero_mask'] = ''
            
        args['--sym'] = self.SymmetryGroup.upper()
        
        args['--K'] = self.NumberOfClasses
            
        # Sampling stuff
        # Find the index(starting at 0) of the selected
        # sampling rate, as used in relion program
        iover = 1 #TODO: check this DROP THIS
        index = ['30','15','7.5','3.7','1.8',
                 '0.9','0.5','0.2','0.1'].index(self.AngularSamplingDeg)
        args['--healpix_order'] = float(index + 1 - iover)
        
        if self.PerformLocalAngularSearch:
            args['--sigma_ang'] = self.LocalAngularSearchRange / 3.
            
        args['--offset_range'] = self.OffsetSearchRangePix
        args['--offset_step']  = self.OffsetSearchStepPix * pow(2, iover)

        args['--j'] = self.NumberOfThreads
        
        # Join in a single line all key, value pairs of the args dict    
        params = ' '.join(['%s %s' % (k, str(v)) for k, v in args.iteritems()])
        params += ' ' + self.AdditionalArguments

        self.insertRunJobStep(self.program, params, self._getIterFiles(self.NumberOfIterations))

    def _insertStepsContinue(self):
        args = {
                '--o': '%s/relion' % self.ExtraDir,
                '--continue': self.optimiserFileName,
                
                '--iter': self.NumberOfIterations,
                
                '--tau2_fudge': self.RegularisationParamT,# should not be changed 
                '--flatten_solvent': '',# use always
                #'--zero_mask': '',# use always. This is confussing since Sjors gui creates the command line
                #                  # with this option
                #                  # but then the program complains about it. 
                '--oversampling': '1',
                '--norm': '',
                '--scale': '',
                }
        iover = 1 #TODO: check this DROP THIS
        index = ['30','15','7.5','3.7','1.8',
                 '0.9','0.5','0.2','0.1'].index(self.AngularSamplingDeg)
        args['--healpix_order'] = float(index + 1 - iover)
        
        if self.PerformLocalAngularSearch:
            args['--sigma_ang'] = self.LocalAngularSearchRange / 3.
            
        args['--offset_range'] = self.OffsetSearchRangePix
        args['--offset_step']  = self.OffsetSearchStepPix * pow(2, iover)

        args['--j'] = self.NumberOfThreads
        
        # Join in a single line all key, value pairs of the args dict    
        params = ' '.join(['%s %s' % (k, str(v)) for k, v in args.iteritems()])
        params += ' ' + self.AdditionalArguments

        self.insertRunJobStep(self.program, params, self._getIterFiles(self.NumberOfIterations))

    def _getExtraOutputs(self):
        return []
    
    def _getFinalSuffix(self):
        return ''       

    def _getPrefixes(self):
        """ This should be redefined in refine protocol. """
        return [''] 

    def _getChangeLabels(self):
        return [MDL_AVG_CHANGES_ORIENTATIONS, MDL_AVG_CHANGES_OFFSETS, MDL_AVG_CHANGES_CLASSES]  

    def _writeIterAngularDist(self, it):
        """ Write the angular distribution. Should be overriden in subclasses. """
        data_angularDist = self.getFilename('angularDist_xmipp', iter=it)    
        data_classes = self._getIterClasses(it)
        mdClasses = MetaData('classes@' + data_classes)
        print "Writing angular distribution to: ", data_angularDist
        for objId in mdClasses:
            ref3d = mdClasses.getValue(MDL_REF3D, objId)
            print "Computing data class %03d" % ref3d
            mdImages = MetaData(('class%06d_images@' % ref3d) + data_classes)
            mdDist = MetaData()
            mdDist.aggregateMdGroupBy(mdImages, AGGR_COUNT, [MDL_ANGLE_ROT, MDL_ANGLE_TILT], MDL_ANGLE_ROT, MDL_WEIGHT)
            mdDist.setValueCol(MDL_ANGLE_PSI, 0.0)
            mdDist.write(('class%06d_angularDist@' % ref3d) + data_angularDist, MD_APPEND)

    def _visualizeDisplayImagesClassification(self):
        """ Read Relion _data.star images file and 
        generate a new metadata with the Xmipp classification standard:
        a 'classes' block and a 'class00000?_images' block per class.
        If the new metadata was already written, it is just shown.
        """
        for it in self._visualizeIterations:
            data_classes = self._getIterClasses(it)
            self.display2D(data_classes, extraParams='--mode metadata --render first')
             