######################################################################
PROJ = crystal_euler2mrc
OBJ  = EM2Angles.o
LIBS = -l$(LIBXMIPP_INTERFACE) -l$(LIBRECONS) -l$(LIBXMIPP) \
       -l$(LIBRECONS_INTERFACE)
