/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameImagesTable.java
 *
 * Created on 22-abr-2010, 12:35:07
 */
package table;

import ij.IJ;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Juanjo Vega
 */
public class JFrameImagesTable extends javax.swing.JFrame {

    private JTable jtImages;
    private ImagesTableModel tableModel;
    private ScoreImagesTableRenderer tableRenderer;

    /** Creates new form JFrameImagesTable */
    public JFrameImagesTable() {
        super();

        initComponents();

        tableModel = new ImagesTableModel();    // Creates table model

        jtImages = new JTable(tableModel);  // Creates table using previous table model.

        tableRenderer = new ScoreImagesTableRenderer();
        jtImages.setDefaultRenderer(ScoreItem.class, tableRenderer);

        jtImages.setRowSelectionAllowed(false);
        jtImages.setColumnSelectionAllowed(false);
        jtImages.setCellSelectionEnabled(false);

        jtImages.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jtImages.setTableHeader(null);
        jtImages.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        jtImages.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() > 1) {
                    int row = jtImages.rowAtPoint(e.getPoint());
                    int col = jtImages.columnAtPoint(e.getPoint());

                    ScoreItem item = (ScoreItem) tableModel.getValueAt(row, col);

                    IJ.open(item.fileName);
                }
            }
        });

        // Adds components to GUI.
        JScrollPane jsPane = new JScrollPane();
        jsPane.setViewportView(jtImages);
        add(jsPane, BorderLayout.CENTER);
    }

    public void loadScoreFile(String scoreFile) {
        clear();

        try {
            BufferedReader input = new BufferedReader(new FileReader(new File(scoreFile)));

            String line = null;
            while ((line = input.readLine()) != null) {
                StringTokenizer st = new StringTokenizer(line, " ");

                tableModel.addItem(new ScoreItem(
                        st.nextToken(),
                        Double.parseDouble(st.nextToken())));
            }
            input.close();

            setTitle("Results: " + tableModel.getColumnCount() + " images");

            if (tableModel.getData().size() > 0) {
                adjustTableSize();
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    public void setWidth(int width) {
        Dimension d = getSize();

        d.width = width;

        setSize(d);
    }

    public void setHeight(int height) {
        Dimension d = getSize();

        d.height = height;

        setSize(d);
        //pack();
    }

    private void adjustTableSize() {
        // Tricky way to calculate table height
        ScoreItem item = ((ScoreItem) tableModel.getValueAt(0, 0));
        item.getImage();

        int fontHeight = getFontMetrics((new JLabel(item.getLabel())).getFont()).getHeight();

        jtImages.setRowHeight(item.h + fontHeight * 2);
        for (int i = 0; i < jtImages.getColumnCount(); i++) {
            jtImages.getColumnModel().getColumn(i).setPreferredWidth(item.w);
        }

        setHeight(item.h + fontHeight * 8);  // Window height.
    }

    public void clear() {
        tableModel.clear();
    }

    public int getRows() {
        return tableModel.getRowCount();
    }

    public int getColumns() {
        return tableModel.getColumnCount();
    }

    public void addImage(ScoreItem scoreItem) {
        tableModel.addItem(scoreItem);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        clear();
    }//GEN-LAST:event_formWindowClosed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
