/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelImageInfo.java
 *
 * Created on 21-ene-2010, 15:50:48
 */
package browser.filebrowsers;

import browser.ICONS_MANAGER;
import browser.LABELS;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Juanjo Vega
 */
public class JPanelImageInfo extends javax.swing.JPanel {

    final static int MARGIN_W = 10;
    final static int MARGIN_H = 25;

    /** Creates new form JPanelImageInfo */
    public JPanelImageInfo() {
        initComponents();

        setPreviewSize(ICONS_MANAGER.DEFAULT_PREVIEW_WIDTH, ICONS_MANAGER.DEFAULT_PREVIEW_HEIGHT);
        jlPreview.setHorizontalAlignment(JLabel.CENTER);

        setImageInfo(null);
    }

    public void setPreviewSize(int width, int height) {
        jlPreview.setPreferredSize(new Dimension(width + MARGIN_W, height + MARGIN_H));
    }

    // Updates preview with current item.
    public void setPreview(Image preview, String info) {
        jlPreview.setIcon(preview != null ? new ImageIcon(preview) : null);
        setImageInfo(info);
    }

    protected void setImageInfo(String info) {
        jlInfo.setText(info != null ? info : "");
    }

    public void clearPreview() {
        setPreview(null, null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jlPreview = new javax.swing.JLabel();
        jpInfo = new javax.swing.JPanel();
        jlInfo = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jlPreview.setBorder(javax.swing.BorderFactory.createTitledBorder(LABELS.TITLE_PREVIEW));
        add(jlPreview, java.awt.BorderLayout.NORTH);

        jpInfo.setLayout(new java.awt.GridBagLayout());

        jlInfo.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jpInfo.add(jlInfo, gridBagConstraints);

        add(jpInfo, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlInfo;
    private javax.swing.JLabel jlPreview;
    private javax.swing.JPanel jpInfo;
    // End of variables declaration//GEN-END:variables
}
