/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class TransformType {
  public final static TransformType NoTransform = new TransformType("NoTransform", XmippDataJNI.NoTransform_get());
  public final static TransformType Standard = new TransformType("Standard", XmippDataJNI.Standard_get());
  public final static TransformType Centered = new TransformType("Centered", XmippDataJNI.Centered_get());
  public final static TransformType Hermitian = new TransformType("Hermitian", XmippDataJNI.Hermitian_get());
  public final static TransformType CentHerm = new TransformType("CentHerm", XmippDataJNI.CentHerm_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TransformType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TransformType.class + " with value " + swigValue);
  }

  private TransformType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TransformType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TransformType(String swigName, TransformType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TransformType[] swigValues = { NoTransform, Standard, Centered, Hermitian, CentHerm };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

