/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class xmippTextualListener extends xmippBaseListener {
  private long swigCPtr;

  protected xmippTextualListener(long cPtr, boolean cMemoryOwn) {
    super(XmippDataJNI.SWIGxmippTextualListenerUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(xmippTextualListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XmippDataJNI.delete_xmippTextualListener(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void OnInitOperation(long _est_it) {
    XmippDataJNI.xmippTextualListener_OnInitOperation(swigCPtr, this, _est_it);
  }

  public void OnProgress(long _it) {
    XmippDataJNI.xmippTextualListener_OnProgress(swigCPtr, this, _it);
  }

  public void OnReportOperation(String _rsOp) {
    XmippDataJNI.xmippTextualListener_OnReportOperation(swigCPtr, this, _rsOp);
  }

  public xmippTextualListener() {
    this(XmippDataJNI.new_xmippTextualListener(), true);
  }

}
