######################################################################
PROJ = recons_test
OBJ  = recons_test.o
LIBS = -l$(LIBXMIPP) -l$(LIBRECONS) -l$(LIBRECONS_VTK) -l$(LIBXMIPP_INTERFACE) \
       -l$(LIBXMIPP_INTERFACE_VTK) $(LIBVTK) -l$(LIBRECONS_INTERFACE)
