######################################################################
PROJ = recons_test
OBJ  = recons_test.o
LIBS = -l$(LIBXMIPP) -l$(LIBXMIPP_INTERFACE) -l$(LIBRECONS)\
       -l$(LIBRECONS_INTERFACE)
