/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameSetSize.java
 *
 * Created on Jun 14, 2010, 4:43:09 PM
 */
package browser.windows;

import java.awt.Dimension;

/**
 *
 * @author Juanjo Vega
 */
public class JFrameSetSize extends javax.swing.JFrame {

    WindowImageOperations window;

    /** Creates new form JFrameSetSize */
    public JFrameSetSize() {
        initComponents();
    }

    public void setWindow(WindowImageOperations window) {
        this.window = window;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jbGetSize = new javax.swing.JButton();
        jsHeight = new javax.swing.JSpinner();
        jsWidth = new javax.swing.JSpinner();
        jbSetSize = new javax.swing.JButton();
        jbPrefGetSizes = new javax.swing.JButton();
        jsPrefHeight = new javax.swing.JSpinner();
        jsPrefWidth = new javax.swing.JSpinner();
        jbSetPrefSize = new javax.swing.JButton();
        jbPack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jbGetSize.setText("Get Size");
        jbGetSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGetSizeActionPerformed(evt);
            }
        });
        getContentPane().add(jbGetSize, new java.awt.GridBagConstraints());

        jsHeight.setBorder(javax.swing.BorderFactory.createTitledBorder("Height: "));
        jsHeight.setPreferredSize(new java.awt.Dimension(60, 55));
        getContentPane().add(jsHeight, new java.awt.GridBagConstraints());

        jsWidth.setBorder(javax.swing.BorderFactory.createTitledBorder("Width: "));
        jsWidth.setPreferredSize(new java.awt.Dimension(60, 55));
        getContentPane().add(jsWidth, new java.awt.GridBagConstraints());

        jbSetSize.setText("Set Size");
        jbSetSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSetSizeActionPerformed(evt);
            }
        });
        getContentPane().add(jbSetSize, new java.awt.GridBagConstraints());

        jbPrefGetSizes.setText("Get Pref. Size");
        jbPrefGetSizes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrefGetSizesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jbPrefGetSizes, gridBagConstraints);

        jsPrefHeight.setBorder(javax.swing.BorderFactory.createTitledBorder("Height: "));
        jsPrefHeight.setPreferredSize(new java.awt.Dimension(60, 55));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jsPrefHeight, gridBagConstraints);

        jsPrefWidth.setBorder(javax.swing.BorderFactory.createTitledBorder("Width: "));
        jsPrefWidth.setPreferredSize(new java.awt.Dimension(60, 55));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jsPrefWidth, gridBagConstraints);

        jbSetPrefSize.setText("Set Pref. Size");
        jbSetPrefSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSetPrefSizeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jbSetPrefSize, gridBagConstraints);

        jbPack.setText("Pack");
        jbPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jbPack, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGetSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGetSizeActionPerformed
        Dimension size = window.getSize();

        jsWidth.setValue(size.width);
        jsHeight.setValue(size.height);
    }//GEN-LAST:event_jbGetSizeActionPerformed

    private void jbSetSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSetSizeActionPerformed
        int height = (Integer) jsHeight.getValue();
        int width = (Integer) jsWidth.getValue();

        window.setSize(width, height);
    }//GEN-LAST:event_jbSetSizeActionPerformed

    private void jbPrefGetSizesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrefGetSizesActionPerformed
        Dimension preferredSize = window.getPreferredSize();

        jsPrefWidth.setValue(preferredSize.width);
        jsPrefHeight.setValue(preferredSize.height);
    }//GEN-LAST:event_jbPrefGetSizesActionPerformed

    private void jbSetPrefSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSetPrefSizeActionPerformed
        int height = (Integer) jsPrefHeight.getValue();
        int width = (Integer) jsPrefWidth.getValue();

        window.setPreferredSize(new Dimension(width, height));
    }//GEN-LAST:event_jbSetPrefSizeActionPerformed

    private void jbPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPackActionPerformed
        window.pack();
    }//GEN-LAST:event_jbPackActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbGetSize;
    private javax.swing.JButton jbPack;
    private javax.swing.JButton jbPrefGetSizes;
    private javax.swing.JButton jbSetPrefSize;
    private javax.swing.JButton jbSetSize;
    private javax.swing.JSpinner jsHeight;
    private javax.swing.JSpinner jsPrefHeight;
    private javax.swing.JSpinner jsPrefWidth;
    private javax.swing.JSpinner jsWidth;
    // End of variables declaration//GEN-END:variables
}
