######################################################################
ifeq ($(HAVE_QT),YES)
   PROJ = ctf_view
endif
OBJ  = 	ctfviewer.o \
        ctfviewer_module.o ctfviewer_module.moc

LIBS = -l$(LIBXMIPP) -l$(LIBRECONS) $(QTLIBS)
EXTRA_INCLUDE_DIRS = -I$(XMIPP_QTDIR)/include
EXTRA_LIB_DIRS     = -L$(XMIPP_QTDIR)/lib
