/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameExtractColumn.java
 *
 * Created on Apr 5, 2011, 5:48:04 PM
 */
package browser.table.micrographs.singlecolumntable;

import browser.table.micrographs.MicrographsTableModel;
import browser.table.micrographs.singlecolumntable.renderers.SingleColumnDoubleRenderer;
import browser.table.micrographs.singlecolumntable.renderers.SingleColumnFileNameRenderer;
import browser.table.micrographs.singlecolumntable.renderers.SingleColumnImageRenderer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Juanjo Vega
 */
public class JFrameExtractColumn extends javax.swing.JFrame {

    TableModelSingleColumn tableModel;

    /** Creates new form JFrameExtractColumn */
    public JFrameExtractColumn(MicrographsTableModel externModel, int column) {
        initComponents();

        tableModel = new TableModelSingleColumn(externModel, column);
        table.setModel(tableModel);

        setRenderer();

        table.setEnabled(false);
    }

    private void setRenderer() {
        TableCellRenderer renderer = null;

        if (tableModel.isImage()) {
            renderer = new SingleColumnImageRenderer();
        } else if (tableModel.isFilename()) {
            renderer = new SingleColumnFileNameRenderer();
        } else if (tableModel.isDouble()) {
            renderer = new SingleColumnDoubleRenderer();
        } else {
            renderer = new DefaultTableCellRenderer();
        }

        table.getColumnModel().getColumn(0).setCellRenderer(renderer);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        spTable.setViewportView(table);

        getContentPane().add(spTable, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane spTable;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
