package xmipp; 
public class MDLabel {
   public static final int MDL_UNDEFINED = -1; ///
   public static final int MDL_FIRST_LABEL = 0;  ///< The label MDL_OBJID is special and should not be used
   public static final int MDL_OBJID = MDL_FIRST_LABEL;  ///< object id (int), NOTE: This label is special and shouldn't be used
   public static final int MDL_ANGLE_COMPARISON = 1;  ///< Angular comparison (see angular_distance.cpp)
   public static final int MDL_ANGLEPSI = 2;  ///< Psi angle of an image (double,degrees)
   public static final int MDL_ANGLEPSI2 = 3;  ///< Psi angle of an image (double,degrees)
   public static final int MDL_ANGLEROT = 4;  ///< Rotation angle of an image (double,degrees)
   public static final int MDL_ANGLEROT2 = 5;  ///< Rotation angle of an image (double,degrees)
   public static final int MDL_ANGLETILT = 6;  ///< Tilting angle of an image (double,degrees)
   public static final int MDL_ANGLETILT2 = 7;  ///< Tilting angle of an image (double,degrees)
   public static final int MDL_ANGLE_Y = 8;    ///< Angle between y-axis and tilt-axis (double, degrees) for untilted micrographs
   public static final int MDL_ANGLE_Y2 = 9;    ///< Angle between y-axis and tilt-axis (double, degrees) for tilted micrographs
   public static final int MDL_ASSOCIATED_IMAGE1 = 10;  ///< Image associated to this object (std::string)
   public static final int MDL_ASSOCIATED_IMAGE2 = 11;  ///< Image associated to this object (std::string)
   public static final int MDL_ASSOCIATED_IMAGE3 = 12;  ///< Image associated to this object (std::string)
   public static final int MDL_ASSOCIATED_IMAGE4 = 13;  ///< Image associated to this object (std::string)
   public static final int MDL_ASSOCIATED_IMAGE5 = 14;  ///< Image associated to this object (std::string)
   public static final int MDL_AVG = 15;  ///< average value (double)
   public static final int MDL_AZIMUTALANGLE = 16;  ///< ctf definition azimutal angle
   public static final int MDL_BGMEAN = 17;  ///< Mean background value for an image
   public static final int MDL_BLOCK = 18;  ///< Current block number (for incremental EM)
   public static final int MDL_CELLX = 19;  ///< Cell location for crystals
   public static final int MDL_CELLY = 20;  ///< Cell location for crystals
   public static final int MDL_CL2D_CHANGES = 21;  ///< Number of changes between iterations
   public static final int MDL_CL2D_SIMILARITY = 22;  ///< Average cross-correlation for the image (double)
   public static final int MDL_CLASSIFICATION_DATA = 23;  ///< Data vector for classification (vector double)
   public static final int MDL_CLASSIFICATION_DATA_SIZE = 24;  ///< Size of data vectors for classification (int)
   public static final int MDL_CLASSIFICATION_DPR_05 = 25;  ///< Differential Phase Residual evaluated at FRC=0.5
   public static final int MDL_CLASSIFICATION_INTRACLASS_DISTANCE = 26;  ///< Average intraclass distance (double)
   public static final int MDL_CLASSIFICATION_FRC_05 = 27;  ///< Digital frequency at which the FRC drops below 0.5 (double)
   public static final int MDL_COMMENT = 28;  ///< A comment for this object /*** NOTE THIS IS A SPECIAL CASE AND SO IS TREATED ***/
   public static final int MDL_COST = 29;  ///< Cost for the image (double)
   public static final int MDL_COUNT = 30;  ///< Number of elements of a type (int) [this is a genereic type do not use to transfer information to another program]
   public static final int MDL_CTFINPUTPARAMS = 31;  ///< Parameters file for the CTF Model (std::string)
   public static final int MDL_CTFMODEL = 32;  ///< Name for the CTF Model (std::string)
   public static final int MDL_CTFMODEL2 = 33;  ///< Name for another CTF model (std::string)
   public static final int MDL_CTF_SAMPLING_RATE = 34;  ///< Sampling rate
   public static final int MDL_CTF_SAMPLING_RATE_Z = 35;  ///< Sampling rate in Z direction
   public static final int MDL_CTF_VOLTAGE = 36;  ///< Microscope voltage (kV)
   public static final int MDL_CTF_DEFOCUSA = 37;  ///< aver (Angage defocusstroms)
   public static final int MDL_CTF_DEFOCUSU = 38;  ///< Defocus U (Angstroms)
   public static final int MDL_CTF_DEFOCUSV = 39;  ///< Defocus V (Angstroms)
   public static final int MDL_CTF_DEFOCUS_ANGLE = 40;  ///< Defocus angle (degrees)
   public static final int MDL_CTF_CS = 41;  ///< Spherical aberration
   public static final int MDL_CTF_CA = 42;  ///< Chromatic aberration
   public static final int MDL_CTF_GROUP = 43;  ///< group images by defocus
   public static final int MDL_CTF_ENERGY_LOSS = 44;  ///< Energy loss
   public static final int MDL_CTF_LENS_STABILITY = 45;  ///< Lens stability
   public static final int MDL_CTF_CONVERGENCE_CONE = 46;  ///< Convergence cone
   public static final int MDL_CTF_LONGITUDINAL_DISPLACEMENT = 47;  ///< Longitudinal displacement
   public static final int MDL_CTF_TRANSVERSAL_DISPLACEMENT = 48;  ///< Transversal displacemente
   public static final int MDL_CTF_Q0 = 49;  ///< Inelastic absorption
   public static final int MDL_CTF_K = 50;  ///< CTF gain
   public static final int MDL_CTFBG_GAUSSIAN_K = 51;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN_SIGMAU = 52;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN_SIGMAV = 53;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN_CU = 54;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN_CV = 55;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN_ANGLE = 56;  ///< CTF Background parameter
   public static final int MDL_CTFBG_SQRT_K = 57;  ///< CTF Background parameter
   public static final int MDL_CTFBG_SQRT_U = 58;  ///< CTF Background parameter
   public static final int MDL_CTFBG_SQRT_V = 59;  ///< CTF Background parameter
   public static final int MDL_CTFBG_SQRT_ANGLE = 60;  ///< CTF Background parameter
   public static final int MDL_CTFBG_BASELINE = 61;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN2_K = 62;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN2_SIGMAU = 63;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN2_SIGMAV = 64;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN2_CU = 65;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN2_CV = 66;  ///< CTF Background parameter
   public static final int MDL_CTFBG_GAUSSIAN2_ANGLE = 67;  ///< CTF Background parameter
   public static final int MDL_CTF_CRITERION_PSDCORRELATION90 = 68;  ///< PSD correlation at 90 degrees
   public static final int MDL_CTF_CRITERION_FIRSTZERORATIO = 69;  ///< First zero ratio
   public static final int MDL_CTF_CRITERION_FIRSTZEROAVG = 70;  ///< First zero average (in Angstroms)
   public static final int MDL_CTF_CRITERION_FIRSTZERODISAGREEMENT = 71;  ///< First zero disagreement with second model (in Angstroms)
   public static final int MDL_CTF_CRITERION_DAMPING = 72;  ///< Minimum damping at border
   public static final int MDL_CTF_CRITERION_PSDRADIALINTEGRAL = 73;  ///< Integral of the radial PSD
   public static final int MDL_CTF_CRITERION_FITTINGSCORE = 74;  ///< Score of the fitting
   public static final int MDL_CTF_CRITERION_FITTINGCORR13 = 75;  ///< Correlation between the 1st and 3rd ring of the CTF
   public static final int MDL_CTF_CRITERION_PSDVARIANCE = 76;  ///< PSD variance
   public static final int MDL_CTF_CRITERION_PSDPCA1VARIANCE = 77;  ///< Variance in the first principal component of the PSDs
   public static final int MDL_CTF_CRITERION_PSDPCARUNSTEST = 78;  ///< Runs test on the projection of the PSD on the first principal component
   public static final int MDL_CTF_CRITERION_NORMALITY = 79;  ///< Normality test between histogram of micrography and gaussian distribution
   public static final int MDL_CTF_XRAY_DIMENSIONS = 80; // Size in pixels of the 3D PSF to be created (Xdim = 80; Ydim = 80; Zdim) ///
   public static final int MDL_CTF_XRAY_LAMBDA = 81;  /// X-ray wavelength (nm)
   public static final int MDL_CTF_XRAY_LENS_TYPE = 82;  ///Algorithm used to generate Xray PSF
   public static final int MDL_MAGNIFICATION = 83;  /// Magnification of the X-ray microscope
   public static final int MDL_CTF_XRAY_OUTER_ZONE_WIDTH = 84;  /// Outermost zone width of the X-ray Fresnel lens (nm)
   public static final int MDL_CTF_XRAY_ZONES_NUMBER = 85; // Number of zones of the X-ray Fresnel lens ///
   public static final int MDL_DATATYPE = 86;  ///< if read from file original image datatype, this is an struct defined in image
   public static final int MDL_DEFGROUP = 87;  ///< Defocus group
   public static final int MDL_DIRECTION = 88;  ///< Direction in 3D
   public static final int MDL_DM3_IDTAG = 89; ///
   public static final int MDL_DM3_NODEID = 90; ///
   public static final int MDL_DM3_NUMBER_TYPE = 91; ///
   public static final int MDL_DM3_PARENTID = 92; ///
   public static final int MDL_DM3_TAGCLASS = 93; ///
   public static final int MDL_DM3_TAGNAME = 94; ///
   public static final int MDL_DM3_SIZE = 95; ///
   public static final int MDL_DM3_VALUE = 96; ///
   public static final int MDL_ENABLED = 97;  ///< Is this image enabled? (int [-1 or 1])
   public static final int MDL_FLIP = 98;  ///< Flip the image? (bool)
   public static final int MDL_IDX = 99;  ///< Index within a list (size_t)
   public static final int MDL_IMAGE_CLASS_COUNT = 100;  ///< Number of images assigned to the same class as this image
   public static final int MDL_IMAGE_CLASS_GROUP = 101;  ///< Name of the class group for this image (metadata with all the images assigned to that class)
   public static final int MDL_IMAGE_CLASS = 102;  ///< Name of the class representative for this image
   public static final int MDL_IMAGE = 103;  ///< Name of an image (std::string)
   public static final int MDL_IMAGE_ORIGINAL = 104;  ///< Name of an image from which MDL_IMAGE is coming from
   public static final int MDL_IMAGE_TILTED = 105;  ///< Name of the tilted images associated to MDL_IMAGE
   public static final int MDL_IMGMD = 106;  ///< Name of Metadata file for all images (string)
   public static final int MDL_INTSCALE = 107;  ///< Intensity scale for an image
   public static final int MDL_ITER = 108;  ///< Current iteration number (int)
   public static final int MDL_K = 109;  ///< //ctf definition K
   public static final int MDL_KERDENSOM_FUNCTIONAL = 110;  ///< Functional value (double)
   public static final int MDL_KERDENSOM_REGULARIZATION = 111;  ///< Regularization value (double)
   public static final int MDL_KERDENSOM_SIGMA = 112;  ///< Sigma value (double)
   public static final int MDL_KSTEST = 113;  ///<KS-test statistics
   public static final int MDL_LL = 114;  ///< contribution of an image to log-likelihood value
   public static final int MDL_MAPTOPOLOGY = 115;  ///< Map topology (KerDenSOM, ...)
   public static final int MDL_MASK = 116;  ///< Name of a mask associated to image
   public static final int MDL_MAXCC = 117;  ///< Maximum cross-correlation for the image (double)
   public static final int MDL_MAX = 118;  ///<maximum value (double)
   public static final int MDL_MICROGRAPH = 119;  ///< Name of a micrograph (std::string)
   public static final int MDL_MICROGRAPH_TILTED = 120;  ///< Name of the corresponding tilted micrograph (std::string)
   public static final int MDL_MIN = 121;  ///<minimum value (double)
   public static final int MDL_MIRRORFRAC = 122;  ///< Mirror fraction for a Maximum Likelihood model
   public static final int MDL_MISSINGREGION_NR = 123;  ///< Number of missing region in subtomogram
   public static final int MDL_MISSINGREGION_TYPE = 124;  ///< Type of missing region in subtomogram
   public static final int MDL_MISSINGREGION_THY0 = 125;  ///< Initial tilt angle in Y for missing region in subtomogram
   public static final int MDL_MISSINGREGION_THYF = 126;  ///< Final tilt angle in Y for missing region in subtomogram
   public static final int MDL_MISSINGREGION_THX0 = 127;  ///< Initial tilt angle in X for missing region in subtomogram
   public static final int MDL_MISSINGREGION_THXF = 128;  ///< Final tilt angle in X for missing region in subtomogram
   public static final int MDL_MODELFRAC = 129;  ///< Model fraction (alpha_k) for a Maximum Likelihood model
   public static final int MDL_NEIGHBORS = 130;  ///< Vector of indexes to points some "neighbors"
   public static final int MDL_NEIGHBORHOOD_RADIUS = 131;  ///< Radius of the neigborhood (radians)
   public static final int MDL_NMA = 132;  ///< Normal mode displacements (vector double)
   public static final int MDL_NMA_MODEFILE = 133;  ///< File with an NMA mode
   public static final int MDL_NOISE_ANGLES = 134;  ///< Noise description for projected angles
   public static final int MDL_NOISE_PARTICLE_COORD = 135;  ///< Noise description for particle's center coordenates (when projecting)
   public static final int MDL_NOISE_PIXEL_LEVEL = 136;  ///< Noise description for pixels' gray level (when projecting)
   public static final int MDL_ORDER = 137;  /// auxiliary label to be used as an index (long)
   public static final int MDL_ORIGINX = 138;  ///< Origin for the image in the X axis (double)
   public static final int MDL_ORIGINY = 139;  ///< Origin for the image in the Y axis (double)
   public static final int MDL_ORIGINZ = 140;  ///< Origin for the image in the Z axis (double)
   public static final int MDL_PICKING_COLOR = 141;  ///< Color for particle picking
   public static final int MDL_PICKING_FAMILY = 142;  ///< Family for particle picking
   public static final int MDL_PICKING_FAMILY_STATE = 143;  ///< Family state for particle picking
   public static final int MDL_PICKING_MICROGRAPH_FAMILY_STATE = 144;  ///< Micrograph family state for particle picking
   public static final int MDL_PICKING_PARTICLE_SIZE = 145;  ///< Particle size for particle picking
   public static final int MDL_PMAX = 146;  ///< Maximum value of normalized probability function (now called "Pmax/sumP") (double)
   public static final int MDL_PRJ_DIMENSIONS = 147; // X = 147;Y dimensions for the generated projections ///
   public static final int MDL_PRJ_TILT_RANGE = 148; // Vector with the initial and final tilt angle values = 148; and step size ///
   public static final int MDL_PRJ_VOL = 149;        // Volume file name to generate projections from ///
   public static final int MDL_PSD = 150;  ///< A Power Spectrum Density file name (std::string)
   public static final int MDL_PSD_ENHANCED = 151;  ///< A enhanced Power Spectrum Density file name (std::string)
   public static final int MDL_RANDOMSEED = 152;  ///< Seed for random number generator
   public static final int MDL_REF3D = 153;  ///< 3D Class to which the image belongs (int)
   public static final int MDL_REF = 154;  ///< Class to which the image belongs (int)
   public static final int MDL_REFMD = 155;  ///< Name of Metadata file for all references(string)
   public static final int MDL_RESOLUTION_DPR = 156;  ///<differential phase residual (double)
   public static final int MDL_RESOLUTION_ERRORL2 = 157;  ///<Error in l2 (double)
   public static final int MDL_RESOLUTION_FRC = 158;  ///<Fourier shell correlation (double)
   public static final int MDL_RESOLUTION_FRCRANDOMNOISE = 159;  ///<Fourier shell correlation noise (double)
   public static final int MDL_RESOLUTION_FREQ = 160;  ///<Frequency in 1/A (double)
   public static final int MDL_RESOLUTION_FREQREAL = 161;  ///< Frequency in A (double)
   public static final int MDL_SAMPLINGRATE = 162;  ///< sampling rate in A/pixel (double)
   public static final int MDL_SAMPLINGRATEX = 163;  ///< sampling rate in A/pixel (double)
   public static final int MDL_SAMPLINGRATEY = 164;  ///< sampling rate in A/pixel (double)
   public static final int MDL_SAMPLINGRATEZ = 165;  ///< sampling rate in A/pixel (double)
   public static final int MDL_SCALE = 166;  ///< scaling factor for an image or volume (double)
   public static final int MDL_SELFILE = 167;  ///< Name of an image (std::string)
   public static final int MDL_SERIE = 168;  ///< A collection of micrographs, e.g. a tilt serie (std::string)
   public static final int MDL_SHIFTX = 169;  ///< Shift for the image in the X axis (double)
   public static final int MDL_SHIFTY = 170;  ///< Shift for the image in the Y axis (double)
   public static final int MDL_SHIFTZ = 171;  ///< Shift for the image in the Z axis (double)
   public static final int MDL_SHIFT_CRYSTALX = 172;  ///< Shift for the image in the X axis (double) for crystals
   public static final int MDL_SHIFT_CRYSTALY = 173;  ///< Shift for the image in the Y axis (double) for crystals
   public static final int MDL_SHIFT_CRYSTALZ = 174;  ///< Shift for the image in the Z axis (double) for crystals
   public static final int MDL_SIGMANOISE = 175;  ///< Standard deviation of the noise in ML model
   public static final int MDL_SIGMAOFFSET = 176;  ///< Standard deviation of the offsets in ML model
   public static final int MDL_SIGNALCHANGE = 177;  ///< Signal change for an image
   public static final int MDL_SPHERICALABERRATION = 178;  ///<ctf definition azimutal angle
   public static final int MDL_STDDEV = 179;  ///<stdandard deviation value (double)
   public static final int MDL_SUM = 180;  ///< Sum of elements of a given type (double) [this is a genereic type do not use to transfer information to another program]
   public static final int MDL_SUMWEIGHT = 181;  ///< Sum of all weights in ML model
   public static final int MDL_SYMNO = 182;  ///< Symmetry number for a projection (used in ART)
   public static final int MDL_TRANSFORMATIONMTRIX = 183;  ///< transformation matrix(vector double)
   public static final int MDL_VOLTAGE = 184;  ///< microscope voltage (double)
   public static final int MDL_WEIGHT = 185;  ///< Weight assigned to the image (double)
   public static final int MDL_WROBUST = 186;  ///< Weight of t-student distribution in robust Maximum likelihood
   public static final int MDL_X = 187;  ///< X component (double)
   public static final int MDL_XINT = 188;  ///< X component (int)
   public static final int MDL_XINTTILT = 189;  ///< X component in tilted micrograph (int)
   public static final int MDL_XSIZE = 190;  ///< X size (int)
   public static final int MDL_Y = 191;  ///< Y component (double)
   public static final int MDL_YINT = 192;  ///< Y component (int)
   public static final int MDL_YINTTILT = 193;  ///< Y component in tilted micrograph (int)
   public static final int MDL_YSIZE = 194;  ///< Y size (int)
   public static final int MDL_Z = 195;  ///< Z component (double)
   public static final int MDL_ZINT = 196;  ///< Z component (int)
   public static final int MDL_ZSCORE = 197;  ///< Z Score (double)
   public static final int MDL_ZSIZE = 198;  ///< Z size (int)
   public static final int MDL_LAST_LABEL = 199;  // **** NOTE ****: Do keep this label always at the end;it is here for looping purposes ///
}
