######################################################################
ifeq ($(HAVE_QT),YES)
   PROJ = edit
endif
OBJ  = 	edit.o \
        textedit.o textedit.moc

LIBS = -l$(LIBXMIPP) $(QTLIBS)
EXTRA_INCLUDE_DIRS = -I$(XMIPP_QTDIR)/include
EXTRA_LIB_DIRS     = -L$(XMIPP_QTDIR)/lib
