
import constants.LABELS;
import javax.swing.JDialog;
import javax.swing.JFileChooser;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameLoad.java
 *
 * Created on May 25, 2010, 11:33:48 AM
 */
/**
 *
 * @author Juanjo Vega
 */
public class JFrameLoad extends JDialog {

    public boolean cancelled;
    private JFileChooser filechooser = new JFileChooser();

    /** Creates new form JFrameLoad */
    public JFrameLoad() {
        super();

        initComponents();

        setLocationRelativeTo(null);
    }

    public String getVolumeFile() {
        return jtfVolume.getText();
    }

    private void enableLoadButton() {
        if (!jtfVolume.getText().isEmpty()) {
            jbLoad.setEnabled(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpControls = new javax.swing.JPanel();
        jpVolume = new javax.swing.JPanel();
        jtfVolume = new javax.swing.JTextField();
        jbVolume = new javax.swing.JButton();
        jpButtons = new javax.swing.JPanel();
        jbLoad = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(LABELS.APP_TITLE);
        setModal(true);

        jpControls.setLayout(new java.awt.GridLayout(2, 0));

        jpVolume.setBorder(javax.swing.BorderFactory.createTitledBorder(LABELS.LABEL_VOLUME));

        jtfVolume.setColumns(20);
        jtfVolume.setEnabled(false);
        jpVolume.add(jtfVolume);

        jbVolume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/load.png"))); // NOI18N
        jbVolume.setText(LABELS.BUTTON_LOAD_FILE);
        jbVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolumeActionPerformed(evt);
            }
        });
        jpVolume.add(jbVolume);

        jpControls.add(jpVolume);

        getContentPane().add(jpControls, java.awt.BorderLayout.CENTER);

        jbLoad.setText(LABELS.BUTTON_OK);
        jbLoad.setEnabled(false);
        jbLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoadActionPerformed(evt);
            }
        });
        jpButtons.add(jbLoad);

        jbCancel.setText(LABELS.BUTTON_CANCEL);
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });
        jpButtons.add(jbCancel);

        getContentPane().add(jpButtons, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        cancelled = true;

        dispose();
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jbLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoadActionPerformed
        cancelled = false;

        dispose();
    }//GEN-LAST:event_jbLoadActionPerformed

    private void jbVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolumeActionPerformed
        if (filechooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            jtfVolume.setText(filechooser.getSelectedFile().getAbsolutePath());
            enableLoadButton();
        }
    }//GEN-LAST:event_jbVolumeActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbLoad;
    private javax.swing.JButton jbVolume;
    private javax.swing.JPanel jpButtons;
    private javax.swing.JPanel jpControls;
    private javax.swing.JPanel jpVolume;
    private javax.swing.JTextField jtfVolume;
    // End of variables declaration//GEN-END:variables
}
