/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Tabsinc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Tabsinc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Tabsinc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XmippDataJNI.delete_Tabsinc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Tabsinc(double dd, int xx) {
    this(XmippDataJNI.new_Tabsinc(dd, xx), true);
  }

  public void filltable() {
    XmippDataJNI.Tabsinc_filltable(swigCPtr, this);
  }

}
