/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface tmpConstants {
  public final static int SWAPTRIG = tmpJNI.SWAPTRIG_get();
  public final static int FORWARD = tmpJNI.FORWARD_get();
  public final static int BACKWARD = tmpJNI.BACKWARD_get();
  public final static int ARTK = tmpJNI.ARTK_get();
  public final static int CAVK = tmpJNI.CAVK_get();
  public final static int COUNT_EQ = tmpJNI.COUNT_EQ_get();
  public final static int CAV = tmpJNI.CAV_get();
  public final static int CAVARTK = tmpJNI.CAVARTK_get();
}
