################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../libraries/reconstruction/adjust_volume_grey_levels.cpp \
../libraries/reconstruction/align2d.cpp \
../libraries/reconstruction/align_tilt_pairs.cpp \
../libraries/reconstruction/angular_commonline.cpp \
../libraries/reconstruction/angular_continuous_assign.cpp \
../libraries/reconstruction/angular_discrete_assign.cpp \
../libraries/reconstruction/angular_distance.cpp \
../libraries/reconstruction/angular_gcar.cpp \
../libraries/reconstruction/angular_neighbourhood.cpp \
../libraries/reconstruction/angular_project_library.cpp \
../libraries/reconstruction/angular_projection_matching.cpp \
../libraries/reconstruction/art_crystal.cpp \
../libraries/reconstruction/art_xray.cpp \
../libraries/reconstruction/base_art_recons.cpp \
../libraries/reconstruction/basic_art.cpp \
../libraries/reconstruction/classify_compare_classes.cpp \
../libraries/reconstruction/classify_evaluate_classes.cpp \
../libraries/reconstruction/ctf_correct_idr.cpp \
../libraries/reconstruction/ctf_correct_wiener3d.cpp \
../libraries/reconstruction/ctf_enhance_psd.cpp \
../libraries/reconstruction/ctf_estimate_from_micrograph.cpp \
../libraries/reconstruction/ctf_estimate_from_psd.cpp \
../libraries/reconstruction/ctf_estimate_psd_with_arma.cpp \
../libraries/reconstruction/ctf_group.cpp \
../libraries/reconstruction/ctf_phase_flip.cpp \
../libraries/reconstruction/ctf_show.cpp \
../libraries/reconstruction/ctf_sort_psds.cpp \
../libraries/reconstruction/denoise.cpp \
../libraries/reconstruction/directions.cpp \
../libraries/reconstruction/fourier_filter.cpp \
../libraries/reconstruction/fourier_projection.cpp \
../libraries/reconstruction/fringe_processing.cpp \
../libraries/reconstruction/image_rotational_pca.cpp \
../libraries/reconstruction/image_rotational_spectra.cpp \
../libraries/reconstruction/image_sort_by_statistics.cpp \
../libraries/reconstruction/mean_shift.cpp \
../libraries/reconstruction/micrograph_automatic_picking.cpp \
../libraries/reconstruction/micrograph_automatic_picking2.cpp \
../libraries/reconstruction/ml2d.cpp \
../libraries/reconstruction/ml_align2d.cpp \
../libraries/reconstruction/ml_refine3d.cpp \
../libraries/reconstruction/ml_tomo.cpp \
../libraries/reconstruction/mlf_align2d.cpp \
../libraries/reconstruction/nma_alignment.cpp \
../libraries/reconstruction/pdb_nma_deform.cpp \
../libraries/reconstruction/phantom_simulate_microscope.cpp \
../libraries/reconstruction/precompute_sampling.cpp \
../libraries/reconstruction/program_extension.cpp \
../libraries/reconstruction/program_filter.cpp \
../libraries/reconstruction/project.cpp \
../libraries/reconstruction/project_crystal.cpp \
../libraries/reconstruction/project_real_shears.cpp \
../libraries/reconstruction/project_tomography.cpp \
../libraries/reconstruction/project_xray.cpp \
../libraries/reconstruction/radon.cpp \
../libraries/reconstruction/recons.cpp \
../libraries/reconstruction/recons_misc.cpp \
../libraries/reconstruction/reconstruct_art.cpp \
../libraries/reconstruction/reconstruct_art_pseudo.cpp \
../libraries/reconstruction/reconstruct_art_xray.cpp \
../libraries/reconstruction/reconstruct_fourier.cpp \
../libraries/reconstruction/reconstruct_wbp.cpp \
../libraries/reconstruction/refinement.cpp \
../libraries/reconstruction/resolution_ibw.cpp \
../libraries/reconstruction/resolution_ssnr.cpp \
../libraries/reconstruction/symmetrize.cpp \
../libraries/reconstruction/threshold.cpp \
../libraries/reconstruction/tomo_align_dual_tilt_series.cpp \
../libraries/reconstruction/tomo_align_refinement.cpp \
../libraries/reconstruction/tomo_align_tilt_series.cpp \
../libraries/reconstruction/tomo_detect_missing_wedge.cpp \
../libraries/reconstruction/tomo_extract_subvolume.cpp \
../libraries/reconstruction/tomo_remove_fluctuations.cpp \
../libraries/reconstruction/transform_downsample.cpp \
../libraries/reconstruction/transform_geometry.cpp \
../libraries/reconstruction/volume_correct_bfactor.cpp \
../libraries/reconstruction/volume_enhance_contrast.cpp \
../libraries/reconstruction/volume_from_pdb.cpp \
../libraries/reconstruction/volume_segment.cpp \
../libraries/reconstruction/volume_to_pseudoatoms.cpp \
../libraries/reconstruction/xray_import.cpp 

OBJS += \
./libraries/reconstruction/adjust_volume_grey_levels.o \
./libraries/reconstruction/align2d.o \
./libraries/reconstruction/align_tilt_pairs.o \
./libraries/reconstruction/angular_commonline.o \
./libraries/reconstruction/angular_continuous_assign.o \
./libraries/reconstruction/angular_discrete_assign.o \
./libraries/reconstruction/angular_distance.o \
./libraries/reconstruction/angular_gcar.o \
./libraries/reconstruction/angular_neighbourhood.o \
./libraries/reconstruction/angular_project_library.o \
./libraries/reconstruction/angular_projection_matching.o \
./libraries/reconstruction/art_crystal.o \
./libraries/reconstruction/art_xray.o \
./libraries/reconstruction/base_art_recons.o \
./libraries/reconstruction/basic_art.o \
./libraries/reconstruction/classify_compare_classes.o \
./libraries/reconstruction/classify_evaluate_classes.o \
./libraries/reconstruction/ctf_correct_idr.o \
./libraries/reconstruction/ctf_correct_wiener3d.o \
./libraries/reconstruction/ctf_enhance_psd.o \
./libraries/reconstruction/ctf_estimate_from_micrograph.o \
./libraries/reconstruction/ctf_estimate_from_psd.o \
./libraries/reconstruction/ctf_estimate_psd_with_arma.o \
./libraries/reconstruction/ctf_group.o \
./libraries/reconstruction/ctf_phase_flip.o \
./libraries/reconstruction/ctf_show.o \
./libraries/reconstruction/ctf_sort_psds.o \
./libraries/reconstruction/denoise.o \
./libraries/reconstruction/directions.o \
./libraries/reconstruction/fourier_filter.o \
./libraries/reconstruction/fourier_projection.o \
./libraries/reconstruction/fringe_processing.o \
./libraries/reconstruction/image_rotational_pca.o \
./libraries/reconstruction/image_rotational_spectra.o \
./libraries/reconstruction/image_sort_by_statistics.o \
./libraries/reconstruction/mean_shift.o \
./libraries/reconstruction/micrograph_automatic_picking.o \
./libraries/reconstruction/micrograph_automatic_picking2.o \
./libraries/reconstruction/ml2d.o \
./libraries/reconstruction/ml_align2d.o \
./libraries/reconstruction/ml_refine3d.o \
./libraries/reconstruction/ml_tomo.o \
./libraries/reconstruction/mlf_align2d.o \
./libraries/reconstruction/nma_alignment.o \
./libraries/reconstruction/pdb_nma_deform.o \
./libraries/reconstruction/phantom_simulate_microscope.o \
./libraries/reconstruction/precompute_sampling.o \
./libraries/reconstruction/program_extension.o \
./libraries/reconstruction/program_filter.o \
./libraries/reconstruction/project.o \
./libraries/reconstruction/project_crystal.o \
./libraries/reconstruction/project_real_shears.o \
./libraries/reconstruction/project_tomography.o \
./libraries/reconstruction/project_xray.o \
./libraries/reconstruction/radon.o \
./libraries/reconstruction/recons.o \
./libraries/reconstruction/recons_misc.o \
./libraries/reconstruction/reconstruct_art.o \
./libraries/reconstruction/reconstruct_art_pseudo.o \
./libraries/reconstruction/reconstruct_art_xray.o \
./libraries/reconstruction/reconstruct_fourier.o \
./libraries/reconstruction/reconstruct_wbp.o \
./libraries/reconstruction/refinement.o \
./libraries/reconstruction/resolution_ibw.o \
./libraries/reconstruction/resolution_ssnr.o \
./libraries/reconstruction/symmetrize.o \
./libraries/reconstruction/threshold.o \
./libraries/reconstruction/tomo_align_dual_tilt_series.o \
./libraries/reconstruction/tomo_align_refinement.o \
./libraries/reconstruction/tomo_align_tilt_series.o \
./libraries/reconstruction/tomo_detect_missing_wedge.o \
./libraries/reconstruction/tomo_extract_subvolume.o \
./libraries/reconstruction/tomo_remove_fluctuations.o \
./libraries/reconstruction/transform_downsample.o \
./libraries/reconstruction/transform_geometry.o \
./libraries/reconstruction/volume_correct_bfactor.o \
./libraries/reconstruction/volume_enhance_contrast.o \
./libraries/reconstruction/volume_from_pdb.o \
./libraries/reconstruction/volume_segment.o \
./libraries/reconstruction/volume_to_pseudoatoms.o \
./libraries/reconstruction/xray_import.o 

CPP_DEPS += \
./libraries/reconstruction/adjust_volume_grey_levels.d \
./libraries/reconstruction/align2d.d \
./libraries/reconstruction/align_tilt_pairs.d \
./libraries/reconstruction/angular_commonline.d \
./libraries/reconstruction/angular_continuous_assign.d \
./libraries/reconstruction/angular_discrete_assign.d \
./libraries/reconstruction/angular_distance.d \
./libraries/reconstruction/angular_gcar.d \
./libraries/reconstruction/angular_neighbourhood.d \
./libraries/reconstruction/angular_project_library.d \
./libraries/reconstruction/angular_projection_matching.d \
./libraries/reconstruction/art_crystal.d \
./libraries/reconstruction/art_xray.d \
./libraries/reconstruction/base_art_recons.d \
./libraries/reconstruction/basic_art.d \
./libraries/reconstruction/classify_compare_classes.d \
./libraries/reconstruction/classify_evaluate_classes.d \
./libraries/reconstruction/ctf_correct_idr.d \
./libraries/reconstruction/ctf_correct_wiener3d.d \
./libraries/reconstruction/ctf_enhance_psd.d \
./libraries/reconstruction/ctf_estimate_from_micrograph.d \
./libraries/reconstruction/ctf_estimate_from_psd.d \
./libraries/reconstruction/ctf_estimate_psd_with_arma.d \
./libraries/reconstruction/ctf_group.d \
./libraries/reconstruction/ctf_phase_flip.d \
./libraries/reconstruction/ctf_show.d \
./libraries/reconstruction/ctf_sort_psds.d \
./libraries/reconstruction/denoise.d \
./libraries/reconstruction/directions.d \
./libraries/reconstruction/fourier_filter.d \
./libraries/reconstruction/fourier_projection.d \
./libraries/reconstruction/fringe_processing.d \
./libraries/reconstruction/image_rotational_pca.d \
./libraries/reconstruction/image_rotational_spectra.d \
./libraries/reconstruction/image_sort_by_statistics.d \
./libraries/reconstruction/mean_shift.d \
./libraries/reconstruction/micrograph_automatic_picking.d \
./libraries/reconstruction/micrograph_automatic_picking2.d \
./libraries/reconstruction/ml2d.d \
./libraries/reconstruction/ml_align2d.d \
./libraries/reconstruction/ml_refine3d.d \
./libraries/reconstruction/ml_tomo.d \
./libraries/reconstruction/mlf_align2d.d \
./libraries/reconstruction/nma_alignment.d \
./libraries/reconstruction/pdb_nma_deform.d \
./libraries/reconstruction/phantom_simulate_microscope.d \
./libraries/reconstruction/precompute_sampling.d \
./libraries/reconstruction/program_extension.d \
./libraries/reconstruction/program_filter.d \
./libraries/reconstruction/project.d \
./libraries/reconstruction/project_crystal.d \
./libraries/reconstruction/project_real_shears.d \
./libraries/reconstruction/project_tomography.d \
./libraries/reconstruction/project_xray.d \
./libraries/reconstruction/radon.d \
./libraries/reconstruction/recons.d \
./libraries/reconstruction/recons_misc.d \
./libraries/reconstruction/reconstruct_art.d \
./libraries/reconstruction/reconstruct_art_pseudo.d \
./libraries/reconstruction/reconstruct_art_xray.d \
./libraries/reconstruction/reconstruct_fourier.d \
./libraries/reconstruction/reconstruct_wbp.d \
./libraries/reconstruction/refinement.d \
./libraries/reconstruction/resolution_ibw.d \
./libraries/reconstruction/resolution_ssnr.d \
./libraries/reconstruction/symmetrize.d \
./libraries/reconstruction/threshold.d \
./libraries/reconstruction/tomo_align_dual_tilt_series.d \
./libraries/reconstruction/tomo_align_refinement.d \
./libraries/reconstruction/tomo_align_tilt_series.d \
./libraries/reconstruction/tomo_detect_missing_wedge.d \
./libraries/reconstruction/tomo_extract_subvolume.d \
./libraries/reconstruction/tomo_remove_fluctuations.d \
./libraries/reconstruction/transform_downsample.d \
./libraries/reconstruction/transform_geometry.d \
./libraries/reconstruction/volume_correct_bfactor.d \
./libraries/reconstruction/volume_enhance_contrast.d \
./libraries/reconstruction/volume_from_pdb.d \
./libraries/reconstruction/volume_segment.d \
./libraries/reconstruction/volume_to_pseudoatoms.d \
./libraries/reconstruction/xray_import.d 


# Each subdirectory must supply rules for building sources it contributes
libraries/reconstruction/%.o: ../libraries/reconstruction/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


