#!/usr/bin/env python

import glob, os, sys

if __name__=="__main__":
    argv     = os.sys.argv
    if not len(argv)==3:
        print "Purpose: Convert EMAN classification into Xmipp selfiles"
        print "Usage: convert_lst2sel"
        print "  <selfile>        : with the original images"
        print "  <directory>      : directory with the cls*.lst files"
        sys.exit(1)
    
    fn_sel=argv[1]
    fn_dir=argv[2]

    # Read original selfile
    sellines=open(fn_sel,'r').read().splitlines()

    # Read ptcl 2 orig
    ptcl2orig=[]
    for line in open(fn_dir+"/ptcl2orig.lst",'r').read().splitlines()[1:]:
        tokens=line.split('\t')
        ptcl2orig.append(int(tokens[0]))

    # Read each cls*.lst
    for fn_lst in glob.glob(fn_dir+"/cls*.lst"):
        print "Processing "+fn_lst
        fn_out=fn_lst[:-4]+".sel"
        fh_out=open(fn_out,'w')

        listlines=open(fn_lst,'r').read().splitlines()
        for line in listlines:
            tokens=line.split("\t")
            if len(tokens)==2:
                ptclIdx=int(tokens[0])
                selIdx=int(ptcl2orig[ptclIdx])
                print >>fh_out,sellines[selIdx]
        fh_out.close()
