/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xmipp_Projection */

#ifndef _Included_xmipp_jni_Projection
#define _Included_xmipp_jni_Projection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xmipp_Projection
 * Method:    projectVolume
 * Signature: (Lxmipp/ImageGeneric;Lxmipp/ImageGeneric;[D)V
 */
JNIEXPORT void JNICALL Java_xmipp_jni_Projection_projectVolume
  (JNIEnv *, jclass, jobject, jobject, jdoubleArray);

/*
 * Class:     xmipp_Projection
 * Method:    entropyOtsuSegmentation
 * Signature: (Lxmipp/ImageGeneric;DZ)D
 */
JNIEXPORT jdouble JNICALL Java_xmipp_jni_Projection_entropyOtsuSegmentation
  (JNIEnv *, jclass, jobject, jdouble, jboolean);

/*
 * Class:     xmipp_Projection
 * Method:    eulerMatrix2Angles
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_xmipp_jni_Projection_eulerMatrix2Angles
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
