/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xmipp_ImageGeneric */

#ifndef _Included_xmipp_ImageGeneric
#define _Included_xmipp_ImageGeneric
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xmipp_ImageGeneric
 * Method:    storeIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_storeIds
  (JNIEnv *, jclass);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_create
  (JNIEnv *, jobject);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_destroy
  (JNIEnv *, jobject);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    read
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_read
  (JNIEnv *, jobject, jstring);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    getStatistics
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_xmipp_ImageGeneric_getStatistics
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
