/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xmipp_ImageGeneric */

#ifndef _Included_xmipp_ImageGeneric
#define _Included_xmipp_ImageGeneric
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xmipp_ImageGeneric
 * Method:    storeIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_storeIds
  (JNIEnv *, jclass);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_create
  (JNIEnv *, jobject);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_destroy
  (JNIEnv *, jobject);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    readHeader
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_readHeader
  (JNIEnv *, jobject, jstring);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    read
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_read
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    write
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_write
  (JNIEnv *, jobject, jstring);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    getArrayByte
 * Signature: (Ljava/lang/String;IIIJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_xmipp_ImageGeneric_getArrayByte
  (JNIEnv *, jclass, jstring, jint, jint, jint, jlong, jint);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    getArrayShort
 * Signature: (Ljava/lang/String;IIIJ)[S
 */
JNIEXPORT jshortArray JNICALL Java_xmipp_ImageGeneric_getArrayShort
  (JNIEnv *, jclass, jstring, jint, jint, jint, jlong, jint);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    getArrayFloat
 * Signature: (Ljava/lang/String;IIIJ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_xmipp_ImageGeneric_getArrayFloat
  (JNIEnv *, jclass, jstring, jint, jint, jint, jlong, jint);

JNIEXPORT jfloatArray JNICALL Java_xmipp_ImageGeneric_setArrayFloat
  (JNIEnv *, jobject, jint, jint, jint, jlong, jint, jfloatArray);
/*
 * Class:     xmipp_ImageGeneric
 * Method:    getStatistics
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_xmipp_ImageGeneric_getStatistics
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
