/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xmipp_ImageGeneric */

#ifndef _Included_xmipp_ImageGeneric
#define _Included_xmipp_ImageGeneric
#ifdef __cplusplus
extern "C" {
#endif
#undef xmipp_ImageGeneric_FIRST_IMAGE
#define xmipp_ImageGeneric_FIRST_IMAGE 1L
#undef xmipp_ImageGeneric_FIRST_SLICE
#define xmipp_ImageGeneric_FIRST_SLICE 1L
#undef xmipp_ImageGeneric_ALL_IMAGES
#define xmipp_ImageGeneric_ALL_IMAGES 0L
#undef xmipp_ImageGeneric_ALL_SLICES
#define xmipp_ImageGeneric_ALL_SLICES 0L
#undef xmipp_ImageGeneric_MID_SLICE
#define xmipp_ImageGeneric_MID_SLICE -1L
#undef xmipp_ImageGeneric_Default
#define xmipp_ImageGeneric_Default -1L
#undef xmipp_ImageGeneric_Unknown_Type
#define xmipp_ImageGeneric_Unknown_Type 0L
#undef xmipp_ImageGeneric_UChar
#define xmipp_ImageGeneric_UChar 1L
#undef xmipp_ImageGeneric_SChar
#define xmipp_ImageGeneric_SChar 2L
#undef xmipp_ImageGeneric_UShort
#define xmipp_ImageGeneric_UShort 3L
#undef xmipp_ImageGeneric_Short
#define xmipp_ImageGeneric_Short 4L
#undef xmipp_ImageGeneric_UInt
#define xmipp_ImageGeneric_UInt 5L
#undef xmipp_ImageGeneric_Int
#define xmipp_ImageGeneric_Int 6L
#undef xmipp_ImageGeneric_Long
#define xmipp_ImageGeneric_Long 7L
#undef xmipp_ImageGeneric_Float
#define xmipp_ImageGeneric_Float 8L
#undef xmipp_ImageGeneric_Double
#define xmipp_ImageGeneric_Double 9L
#undef xmipp_ImageGeneric_ComplexShort
#define xmipp_ImageGeneric_ComplexShort 10L
#undef xmipp_ImageGeneric_ComplexInt
#define xmipp_ImageGeneric_ComplexInt 11L
#undef xmipp_ImageGeneric_ComplexFloat
#define xmipp_ImageGeneric_ComplexFloat 12L
#undef xmipp_ImageGeneric_ComplexDouble
#define xmipp_ImageGeneric_ComplexDouble 13L
#undef xmipp_ImageGeneric_Bool
#define xmipp_ImageGeneric_Bool 14L
#undef xmipp_ImageGeneric_LastEntry
#define xmipp_ImageGeneric_LastEntry 15L
/*
 * Class:     xmipp_ImageGeneric
 * Method:    storeIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_storeIds
  (JNIEnv *, jclass);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_create
  (JNIEnv *, jobject);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_destroy
  (JNIEnv *, jobject);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    readHeader
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_readHeader
  (JNIEnv *, jobject, jstring);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    read
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_read
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    write
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_write
  (JNIEnv *, jobject, jstring);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    getArrayByte
 * Signature: (Ljava/lang/String;IIIJI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_xmipp_ImageGeneric_getArrayByte
  (JNIEnv *, jclass, jstring, jint, jint, jint, jlong, jint);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    getArrayShort
 * Signature: (Ljava/lang/String;IIIJI)[S
 */
JNIEXPORT jshortArray JNICALL Java_xmipp_ImageGeneric_getArrayShort
  (JNIEnv *, jclass, jstring, jint, jint, jint, jlong, jint);

/*
 * Class:     xmipp_ImageGeneric
 * Method:    getArrayFloat
 * Signature: (Ljava/lang/String;IIIJI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_xmipp_ImageGeneric_getArrayFloat
  (JNIEnv *, jclass, jstring, jint, jint, jint, jlong, jint);

JNIEXPORT jfloatArray JNICALL Java_xmipp_ImageGeneric_setArrayFloat
  (JNIEnv *, jobject, jint, jint, jint, jlong, jint, jfloatArray);
/*
 * Class:     xmipp_ImageGeneric
 * Method:    getStatistics
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_xmipp_ImageGeneric_getStatistics
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
