/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xmipp_ImageGeneric_ */

#ifndef _Included_xmipp_ImageGeneric_
#define _Included_xmipp_ImageGeneric_
#ifdef __cplusplus
extern "C" {
#endif
#undef xmipp_ImageGeneric__FIRST_IMAGE
#define xmipp_ImageGeneric__FIRST_IMAGE 1LL
#undef xmipp_ImageGeneric__FIRST_SLICE
#define xmipp_ImageGeneric__FIRST_SLICE 1L
#undef xmipp_ImageGeneric__ALL_IMAGES
#define xmipp_ImageGeneric__ALL_IMAGES 0LL
#undef xmipp_ImageGeneric__ALL_SLICES
#define xmipp_ImageGeneric__ALL_SLICES 0L
#undef xmipp_ImageGeneric__MID_SLICE
#define xmipp_ImageGeneric__MID_SLICE -1L
#undef xmipp_ImageGeneric__Default
#define xmipp_ImageGeneric__Default -1L
#undef xmipp_ImageGeneric__Unknown_Type
#define xmipp_ImageGeneric__Unknown_Type 0L
#undef xmipp_ImageGeneric__UChar
#define xmipp_ImageGeneric__UChar 1L
#undef xmipp_ImageGeneric__SChar
#define xmipp_ImageGeneric__SChar 2L
#undef xmipp_ImageGeneric__UShort
#define xmipp_ImageGeneric__UShort 3L
#undef xmipp_ImageGeneric__Short
#define xmipp_ImageGeneric__Short 4L
#undef xmipp_ImageGeneric__UInt
#define xmipp_ImageGeneric__UInt 5L
#undef xmipp_ImageGeneric__Int
#define xmipp_ImageGeneric__Int 6L
#undef xmipp_ImageGeneric__Long
#define xmipp_ImageGeneric__Long 7L
#undef xmipp_ImageGeneric__Float
#define xmipp_ImageGeneric__Float 8L
#undef xmipp_ImageGeneric__Double
#define xmipp_ImageGeneric__Double 9L
#undef xmipp_ImageGeneric__ComplexShort
#define xmipp_ImageGeneric__ComplexShort 10L
#undef xmipp_ImageGeneric__ComplexInt
#define xmipp_ImageGeneric__ComplexInt 11L
#undef xmipp_ImageGeneric__ComplexFloat
#define xmipp_ImageGeneric__ComplexFloat 12L
#undef xmipp_ImageGeneric__ComplexDouble
#define xmipp_ImageGeneric__ComplexDouble 13L
#undef xmipp_ImageGeneric__Bool
#define xmipp_ImageGeneric__Bool 14L
#undef xmipp_ImageGeneric__LastEntry
#define xmipp_ImageGeneric__LastEntry 15L
/*
 * Class:     xmipp_ImageGeneric_
 * Method:    storeIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_1_storeIds
  (JNIEnv *, jclass);

/*
 * Class:     xmipp_ImageGeneric_
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_1_create
  (JNIEnv *, jobject);

/*
 * Class:     xmipp_ImageGeneric_
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_1_destroy
  (JNIEnv *, jobject);

/*
 * Class:     xmipp_ImageGeneric_
 * Method:    readHeader
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_1_readHeader
  (JNIEnv *, jobject, jstring);

/*
 * Class:     xmipp_ImageGeneric_
 * Method:    read
 * Signature: (Ljava/lang/String;IIIJ)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_1_read
  (JNIEnv *, jobject, jstring, jint, jint, jint, jlong);

/*
 * Class:     xmipp_ImageGeneric_
 * Method:    getArrayByte
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_xmipp_ImageGeneric_1_getArrayByte
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     xmipp_ImageGeneric_
 * Method:    getArrayShort
 * Signature: (II)[S
 */
JNIEXPORT jshortArray JNICALL Java_xmipp_ImageGeneric_1_getArrayShort
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     xmipp_ImageGeneric_
 * Method:    getArrayFloat
 * Signature: (II)[F
 */
JNIEXPORT jfloatArray JNICALL Java_xmipp_ImageGeneric_1_getArrayFloat
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     xmipp_ImageGeneric_
 * Method:    write
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_1_write
  (JNIEnv *, jobject, jstring);

/*
 * Class:     xmipp_ImageGeneric_
 * Method:    setArrayByte
 * Signature: (IIIJ[BI)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_1_setArrayByte
  (JNIEnv *, jobject, jint, jint, jint, jlong, jbyteArray, jint);

/*
 * Class:     xmipp_ImageGeneric_
 * Method:    setArrayShort
 * Signature: (IIIJ[SI)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_1_setArrayShort
  (JNIEnv *, jobject, jint, jint, jint, jlong, jshortArray, jint);

/*
 * Class:     xmipp_ImageGeneric_
 * Method:    setArrayFloat
 * Signature: (IIIJ[FI)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_1_setArrayFloat
  (JNIEnv *, jobject, jint, jint, jint, jlong, jfloatArray, jint);

/*
 * Class:     xmipp_ImageGeneric_
 * Method:    printShape
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_1_printShape
  (JNIEnv *, jobject);

/*
 * Class:     xmipp_ImageGeneric_
 * Method:    getStatistics
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_xmipp_ImageGeneric_1_getStatistics
  (JNIEnv *, jobject);

/*
 * Class:     xmipp_ImageGeneric_
 * Method:    setXmippOrigin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_1_setXmippOrigin
  (JNIEnv *, jobject);

/*
 * Class:     xmipp_ImageGeneric_
 * Method:    convertPSD
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageGeneric_1_convertPSD
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
