/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xmipp_ImageDouble */

#ifndef _Included_xmipp_ImageDouble
#define _Included_xmipp_ImageDouble
#ifdef __cplusplus
extern "C" {
#endif
#undef xmipp_ImageDouble_INDEX_WIDTH
#define xmipp_ImageDouble_INDEX_WIDTH 0L
#undef xmipp_ImageDouble_INDEX_HEIGHT
#define xmipp_ImageDouble_INDEX_HEIGHT 1L
#undef xmipp_ImageDouble_INDEX_DEPTH
#define xmipp_ImageDouble_INDEX_DEPTH 2L
/*
 * Class:     xmipp_ImageDouble
 * Method:    storeIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageDouble_storeIds
  (JNIEnv *, jclass);

/*
 * Class:     xmipp_ImageDouble
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageDouble_create
  (JNIEnv *, jobject);

/*
 * Class:     xmipp_ImageDouble
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageDouble_destroy
  (JNIEnv *, jobject);

/*
 * Class:     xmipp_ImageDouble
 * Method:    read_
 * Signature: (Ljava/lang/String;ZJ)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageDouble_read_1
  (JNIEnv *, jobject, jstring, jboolean, jlong);

/*
 * Class:     xmipp_ImageDouble
 * Method:    readPreview_
 * Signature: (Ljava/lang/String;IIIJ)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageDouble_readPreview_1
  (JNIEnv *, jobject, jstring, jint, jint, jint, jlong);

/*
 * Class:     xmipp_ImageDouble
 * Method:    write
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageDouble_write
  (JNIEnv *, jobject, jstring);

/*
 * Class:     xmipp_ImageDouble
 * Method:    getData
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_xmipp_ImageDouble_getData
  (JNIEnv *, jobject);

/*
 * Class:     xmipp_ImageDouble
 * Method:    getPixel
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_xmipp_ImageDouble_getPixel
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     xmipp_ImageDouble
 * Method:    setPixel
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageDouble_setPixel
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     xmipp_ImageDouble
 * Method:    getVoxel
 * Signature: (III)D
 */
JNIEXPORT jdouble JNICALL Java_xmipp_ImageDouble_getVoxel
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     xmipp_ImageDouble
 * Method:    setVoxel
 * Signature: (IIID)V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageDouble_setVoxel
  (JNIEnv *, jobject, jint, jint, jint, jdouble);

/*
 * Class:     xmipp_ImageDouble
 * Method:    convertPSD
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageDouble_convertPSD
  (JNIEnv *, jobject);

/*
 * Class:     xmipp_ImageDouble
 * Method:    getDimensions_
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_xmipp_ImageDouble_getDimensions_1
  (JNIEnv *, jobject);

/*
 * Class:     xmipp_ImageDouble
 * Method:    getNImages_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_xmipp_ImageDouble_getNImages_1
  (JNIEnv *, jobject);

/*
 * Class:     xmipp_ImageDouble
 * Method:    printShape
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xmipp_ImageDouble_printShape
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
