/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xmipp_TiltPairAligner */

#ifndef _Included_xmipp_TiltPairAligner
#define _Included_xmipp_TiltPairAligner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xmipp_TiltPairAligner
 * Method:    addParticleToAligner
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_xmipp_TiltPairAligner_addParticleToAligner
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
