#!/bin/sh

VERSION=2.0
NEW_NAME=xmipp_find_center2d

# Warn user
echo "** Warning! This program name is deprecated as of Xmipp version" $VERSION
echo "** Please use" $NEW_NAME "instead"
echo "** Continuing execution..."

# Call real program
$NEW_NAME "$@"
