######################################################################
ifeq ($(HAVE_QT),YES)
   PROJ = show
endif
OBJ  = show.o
        
LIBS = -l$(LIBXMIPP_GRAPHICS) -l$(LIBXMIPP_INTERFACE_VTK) $(LIBVTK)\
       -l$(LIBXMIPP) -l$(LIBCLASSIF) -lqt 
EXTRA_INCLUDE_DIRS = -I$(XMIPP_QTDIR)/include
EXTRA_LIB_DIRS     = -L$(XMIPP_QTDIR)/lib
