/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogTextFile.java
 *
 * Created on 12-dic-2010, 0:46:53
 */
package xmipp.viewer.metadata.dialogs;

import ij.IJ;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import javax.swing.JDialog;

/**
 *
 * @author Juanjo Vega
 */
public class JDialogTextFile extends JDialog {

    /** Creates new form JDialogTextFile */
    public JDialogTextFile() {
        super();

        initComponents();
    }

    public JDialogTextFile(String filename, String title) {
        this();

        loadFile(filename);
        setTitle(title);
    }

    public void loadFile(String filename) {
        File file = new File(filename);

        try {
            BufferedReader inputStream = new BufferedReader(new FileReader(file));

            String line;
            StringBuilder text = new StringBuilder();
            while ((line = inputStream.readLine()) != null) {
                text.append(line + "\n");
            }

            jepEditorPane.setText(text.toString());
        } catch (FileNotFoundException fnfex) {
            IJ.error("File not found: " + fnfex.getMessage());
        } catch (Exception ex) {
            ex.printStackTrace(System.err);
            IJ.error(ex.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspEditor = new javax.swing.JScrollPane();
        jepEditorPane = new javax.swing.JEditorPane();
        jpButtons = new javax.swing.JPanel();
        jbOk = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jepEditorPane.setEditable(false);
        jepEditorPane.setPreferredSize(new java.awt.Dimension(300, 300));
        jspEditor.setViewportView(jepEditorPane);

        getContentPane().add(jspEditor, java.awt.BorderLayout.CENTER);

        jbOk.setText("Ok");
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });
        jpButtons.add(jbOk);

        getContentPane().add(jpButtons, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jbOkActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jbOk.requestFocus();
    }//GEN-LAST:event_formWindowOpened
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbOk;
    private javax.swing.JEditorPane jepEditorPane;
    private javax.swing.JPanel jpButtons;
    private javax.swing.JScrollPane jspEditor;
    // End of variables declaration//GEN-END:variables
}
