/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogColumnsSelector.java
 *
 * Created on Jul 5, 2011, 12:42:57 PM
 */
package xmipp.viewer.metadata.dialogs;

import xmipp.utils.XmippLabel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JDialog;
import xmipp.viewer.metadata.METADATA_LABELS;
import xmipp.viewer.metadata.models.MetaDataTableModel;
import xmipp.viewer.metadata.renderers.CheckBoxRenderer;

/**
 *
 * @author Juanjo Vega
 */
public class JDialogColumnsSelector extends JDialog {

    protected ColumnsListModel columnsModel;
    protected boolean option;

    /** Creates new form JDialogColumnsSelector */
    public JDialogColumnsSelector() {
        super();

        setTitle(METADATA_LABELS.TITLE_COLUMNS_SELECTOR);

        initComponents();

        setModal(true);

        jlist.setCellRenderer(new CheckBoxRenderer());

        jlist.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent me) {
                int selectedIndex = jlist.locationToIndex(me.getPoint());
                if (selectedIndex < 0) {
                    return;
                }
                columnsModel.toggleItem(selectedIndex);
            }
        });
    }

    public void setStates(boolean states[]) {
        columnsModel.setStates(states);
    }

    public boolean[] getStates() {
        return columnsModel.getStates();
    }

    public void setModel(MetaDataTableModel tableModel) {
        columnsModel = new ColumnsListModel(tableModel.getLabels());
        jlist.setModel(columnsModel);
    }

    public boolean hasSelectedOK() {
        return option;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspList = new javax.swing.JScrollPane();
        jlist = new javax.swing.JList();
        jpButtons = new javax.swing.JPanel();
        jbOk = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jspList.setViewportView(jlist);

        getContentPane().add(jspList, java.awt.BorderLayout.CENTER);

        jbOk.setText(XmippLabel.BUTTON_OK);
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });
        jpButtons.add(jbOk);

        jbCancel.setText(XmippLabel.BUTTON_CANCEL);
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });
        jpButtons.add(jbCancel);

        getContentPane().add(jpButtons, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
        option = true;
        dispose();
    }//GEN-LAST:event_jbOkActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        option = false;
        dispose();
    }//GEN-LAST:event_jbCancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOk;
    private javax.swing.JList jlist;
    private javax.swing.JPanel jpButtons;
    private javax.swing.JScrollPane jspList;
    // End of variables declaration//GEN-END:variables
}
