#!/bin/sh

if [ $# != 0 ] ; then
   echo "; XMIPP_3 * /home/roberto/Ribosome"
   echo "; image enabled" 
   for i in $1
   do
      echo $i 1
   done
else 
   echo "Usage: selfile_create \"pattern\" > selfile"
fi

