######################################################################
NEEDS_MPI = true

PROJ = MPI_angular_predict
OBJ  = MPI_angular_predict.o
LIBS = -l$(LIBXMIPP) -l$(LIBCLASSIF) -l$(LIBRECONS_CLASSIF) -l$(LIBRECONS) \
       -l$(LIBRECONS_VTK) -l$(LIBXMIPP_INTERFACE_VTK) $(LIBVTK)
