/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameRotSpectra.java
 *
 * Created on Sep 23, 2011, 4:31:29 PM
 */
package rotspectra;

import browser.DEBUG;
import browser.table.models.ImagesRowHeaderModel;
import browser.table.renderers.RowHeaderRenderer;
import browser.windows.ImagesWindowFactory;
import ij.IJ;
import java.awt.Component;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Enumeration;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JSeparator;
import javax.swing.LookAndFeel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Juanjo Vega
 */
public class JFrameRotSpectra extends javax.swing.JFrame {

    private RotSpectraTableModel tableModel;
    //private ImagesTableColumnModel columnModel;
    private ImagesRowHeaderModel rowHeaderModel;
    private JList rowHeader;
    private RotSpectraRenderer renderer = new RotSpectraRenderer(128, 128);
    private JPopUpMenuTable jpopUpMenuTable;

    public static void main(String args[]) {
        try {
            String dir = "/data2/MicrographPreprocessing/2D/RotSpectra/run_001/";
            String filenameClasses = dir + "results_classes.xmd";
            String filenameVectors = dir + "results_vectors.xmd";
            String vectorsData = dir + "results_vectors.xmd.raw";

            JFrameRotSpectra frame = new JFrameRotSpectra(filenameClasses, filenameVectors, vectorsData);
            ImagesWindowFactory.setConvenientSize(frame);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        } catch (Exception ex) {
            DEBUG.printException(ex);
        }
    }

    public JFrameRotSpectra(String fnClasses, String fnVectors, String fnData) {
        super();

        try {
            tableModel = new RotSpectraTableModel(fnClasses, fnVectors, fnData);

            initComponents();

            setTitle("@TODO Set title.");//tableModel.getTitle());

            table.setDefaultRenderer(RotSpectraVector.class, renderer);

            setRowHeader();

            packColumns();
            packRows();

            jpopUpMenuTable = new JPopUpMenuTable();
        } catch (Exception e) {
            DEBUG.printException(e);
            IJ.error(e.getMessage());
        }
    }

    private void setRowHeader() {
        rowHeaderModel = new ImagesRowHeaderModel(table, 1);

        rowHeader = new JList();
        rowHeader.setModel(rowHeaderModel);

        LookAndFeel.installColorsAndFont(rowHeader, "TableHeader.background",
                "TableHeader.foreground", "TableHeader.font");

        rowHeader.setCellRenderer(new RowHeaderRenderer());

        jspTable.setRowHeaderView(rowHeader);
//        rowHeader.repaint();
    }

    private void packRows() {
        //  Row header.
        rowHeader.setFixedCellHeight(renderer.getHeight());

        for (int row = 0; row < table.getRowCount(); row++) {
            table.setRowHeight(row, renderer.getHeight());
        }
    }

    private void packColumns() {
        Enumeration<TableColumn> columns = table.getColumnModel().getColumns();
        while (columns.hasMoreElements()) {
            columns.nextElement().setPreferredWidth(renderer.getWidth());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(tableModel);
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jspTable.setViewportView(table);

        getContentPane().add(jspTable, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jspTable;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    class JPopUpMenuTable extends JPopupMenu {

        protected Point location;
        protected JMenuItem jmiTest = new JMenuItem("@TODO fill: item1");
        protected JMenuItem jmiTest2 = new JMenuItem("@TODO fill: item2");

        public JPopUpMenuTable() {
            add(jmiTest);
            add(new JSeparator());
            add(jmiTest2);

            jmiTest.addActionListener(new ActionListener() {

                public void actionPerformed(ActionEvent e) {
                }
            });
        }

        public void show(Component cmpnt, Point location) {
            this.location = location;
            show(cmpnt, location.x, location.y);
        }
    }
}
