######################################################################
ifeq ($(HAVE_TIFF),YES)
   PROJ = tiff2raw
endif
OBJ  = tiff2raw.o
LIBS = -ltiff
EXTRA_LIB_DIRS = -L$(XMIPP_TIFFLIBDIR)
EXTRA_INCLUDE_DIRS = -I $(XMIPP_TIFFINCDIR)
