######################################################################
ifeq ($(HAVE_TIFF),YES)
   PROJ = tiff2raw
endif
OBJ  = tiff2raw.o
LIBS = -ltiff
EXTRA_LIB_DIRS = -L $(XMIPP_TIFFDIR)/lib
EXTRA_INCLUDE_DIRS = -I $(XMIPP_TIFFDIR)/include
