
import constants.LABELS;
import javax.swing.JDialog;
import javax.swing.JFileChooser;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameLoad.java
 *
 * Created on May 25, 2010, 11:33:48 AM
 */
/**
 *
 * @author Juanjo Vega
 */
public class JFrameLoad extends JDialog {

    public boolean cancelled;
    private JFileChooser filechooser = new JFileChooser();

    /** Creates new form JFrameLoad */
    public JFrameLoad() {
        super();

        initComponents();

        setLocationRelativeTo(null);
    }

    public String getVolumeFile() {
        String volumeFile = jtfVolume.getText();
        return volumeFile.trim().isEmpty() ? null : volumeFile;
    }

    public String getEulerAnglesFile() {
        if (!jcbAngles.isSelected()) {
            return null;
        }

        String anglesFile = jtfEulerAngles.getText();
        return anglesFile.trim().isEmpty() ? null : anglesFile;
    }

    private void enableLoadButton() {
        if (!jtfVolume.getText().isEmpty()
                && (!jcbAngles.isSelected() || !jtfEulerAngles.getText().isEmpty())) {
            jbLoad.setEnabled(true);
        } else {
            jbLoad.setEnabled(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpControls = new javax.swing.JPanel();
        jlVolume = new javax.swing.JLabel();
        jtfVolume = new javax.swing.JTextField();
        jbVolume = new javax.swing.JButton();
        jcbAngles = new javax.swing.JCheckBox();
        jtfEulerAngles = new javax.swing.JTextField();
        jbAngles = new javax.swing.JButton();
        jpButtons = new javax.swing.JPanel();
        jbLoad = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(LABELS.APP_TITLE);
        setModal(true);

        jpControls.setLayout(new java.awt.GridBagLayout());

        jlVolume.setText(LABELS.LABEL_VOLUME_FILE);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jpControls.add(jlVolume, gridBagConstraints);

        jtfVolume.setColumns(20);
        jtfVolume.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jpControls.add(jtfVolume, gridBagConstraints);

        jbVolume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/load.png"))); // NOI18N
        jbVolume.setText(LABELS.BUTTON_LOAD_FILE);
        jbVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolumeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jpControls.add(jbVolume, gridBagConstraints);

        jcbAngles.setSelected(true);
        jcbAngles.setText(LABELS.LABEL_ANGLES_FILE);
        jcbAngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAnglesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jpControls.add(jcbAngles, gridBagConstraints);

        jtfEulerAngles.setColumns(20);
        jtfEulerAngles.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jpControls.add(jtfEulerAngles, gridBagConstraints);

        jbAngles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/load.png"))); // NOI18N
        jbAngles.setText(LABELS.BUTTON_LOAD_FILE);
        jbAngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnglesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jpControls.add(jbAngles, gridBagConstraints);

        getContentPane().add(jpControls, java.awt.BorderLayout.CENTER);

        jbLoad.setText(LABELS.BUTTON_OK);
        jbLoad.setEnabled(false);
        jbLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoadActionPerformed(evt);
            }
        });
        jpButtons.add(jbLoad);

        jbCancel.setText(LABELS.BUTTON_CANCEL);
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });
        jpButtons.add(jbCancel);

        getContentPane().add(jpButtons, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        cancelled = true;

        dispose();
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jbLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoadActionPerformed
        cancelled = false;

        dispose();
    }//GEN-LAST:event_jbLoadActionPerformed

    private void jbVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolumeActionPerformed
        if (filechooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            jtfVolume.setText(filechooser.getSelectedFile().getAbsolutePath());
            enableLoadButton();
        }
    }//GEN-LAST:event_jbVolumeActionPerformed

    private void jbAnglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnglesActionPerformed
        if (filechooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            jtfEulerAngles.setText(filechooser.getSelectedFile().getAbsolutePath());
            enableLoadButton();
        }
    }//GEN-LAST:event_jbAnglesActionPerformed

    private void jcbAnglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAnglesActionPerformed
        enableLoadButton();
        jbAngles.setEnabled(jcbAngles.isSelected());
    }//GEN-LAST:event_jcbAnglesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAngles;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbLoad;
    private javax.swing.JButton jbVolume;
    private javax.swing.JCheckBox jcbAngles;
    private javax.swing.JLabel jlVolume;
    private javax.swing.JPanel jpButtons;
    private javax.swing.JPanel jpControls;
    private javax.swing.JTextField jtfEulerAngles;
    private javax.swing.JTextField jtfVolume;
    // End of variables declaration//GEN-END:variables
}
