/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class MultidimArrayd {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MultidimArrayd(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MultidimArrayd obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XmippDataJNI.delete_MultidimArrayd(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(SWIGTYPE_p_double value) {
    XmippDataJNI.MultidimArrayd_data_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getData() {
    long cPtr = XmippDataJNI.MultidimArrayd_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setDestroyData(boolean value) {
    XmippDataJNI.MultidimArrayd_destroyData_set(swigCPtr, this, value);
  }

  public boolean getDestroyData() {
    return XmippDataJNI.MultidimArrayd_destroyData_get(swigCPtr, this);
  }

  public void setNdim(long value) {
    XmippDataJNI.MultidimArrayd_ndim_set(swigCPtr, this, value);
  }

  public long getNdim() {
    return XmippDataJNI.MultidimArrayd_ndim_get(swigCPtr, this);
  }

  public void setZdim(int value) {
    XmippDataJNI.MultidimArrayd_zdim_set(swigCPtr, this, value);
  }

  public int getZdim() {
    return XmippDataJNI.MultidimArrayd_zdim_get(swigCPtr, this);
  }

  public void setYdim(int value) {
    XmippDataJNI.MultidimArrayd_ydim_set(swigCPtr, this, value);
  }

  public int getYdim() {
    return XmippDataJNI.MultidimArrayd_ydim_get(swigCPtr, this);
  }

  public void setXdim(int value) {
    XmippDataJNI.MultidimArrayd_xdim_set(swigCPtr, this, value);
  }

  public int getXdim() {
    return XmippDataJNI.MultidimArrayd_xdim_get(swigCPtr, this);
  }

  public void setYxdim(long value) {
    XmippDataJNI.MultidimArrayd_yxdim_set(swigCPtr, this, value);
  }

  public long getYxdim() {
    return XmippDataJNI.MultidimArrayd_yxdim_get(swigCPtr, this);
  }

  public void setZyxdim(long value) {
    XmippDataJNI.MultidimArrayd_zyxdim_set(swigCPtr, this, value);
  }

  public long getZyxdim() {
    return XmippDataJNI.MultidimArrayd_zyxdim_get(swigCPtr, this);
  }

  public void setNzyxdim(long value) {
    XmippDataJNI.MultidimArrayd_nzyxdim_set(swigCPtr, this, value);
  }

  public long getNzyxdim() {
    return XmippDataJNI.MultidimArrayd_nzyxdim_get(swigCPtr, this);
  }

  public void setZinit(int value) {
    XmippDataJNI.MultidimArrayd_zinit_set(swigCPtr, this, value);
  }

  public int getZinit() {
    return XmippDataJNI.MultidimArrayd_zinit_get(swigCPtr, this);
  }

  public void setYinit(int value) {
    XmippDataJNI.MultidimArrayd_yinit_set(swigCPtr, this, value);
  }

  public int getYinit() {
    return XmippDataJNI.MultidimArrayd_yinit_get(swigCPtr, this);
  }

  public void setXinit(int value) {
    XmippDataJNI.MultidimArrayd_xinit_set(swigCPtr, this, value);
  }

  public int getXinit() {
    return XmippDataJNI.MultidimArrayd_xinit_get(swigCPtr, this);
  }

  public void setMmapOn(boolean value) {
    XmippDataJNI.MultidimArrayd_mmapOn_set(swigCPtr, this, value);
  }

  public boolean getMmapOn() {
    return XmippDataJNI.MultidimArrayd_mmapOn_get(swigCPtr, this);
  }

  public void setMapFile(FileName value) {
    XmippDataJNI.MultidimArrayd_mapFile_set(swigCPtr, this, FileName.getCPtr(value), value);
  }

  public FileName getMapFile() {
    long cPtr = XmippDataJNI.MultidimArrayd_mapFile_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FileName(cPtr, false);
  }

  public void setMFd(int value) {
    XmippDataJNI.MultidimArrayd_mFd_set(swigCPtr, this, value);
  }

  public int getMFd() {
    return XmippDataJNI.MultidimArrayd_mFd_get(swigCPtr, this);
  }

  public MultidimArrayd() {
    this(XmippDataJNI.new_MultidimArrayd__SWIG_0(), true);
  }

  public MultidimArrayd(long Ndim, int Zdim, int Ydim, int Xdim) {
    this(XmippDataJNI.new_MultidimArrayd__SWIG_1(Ndim, Zdim, Ydim, Xdim), true);
  }

  public MultidimArrayd(int Zdim, int Ydim, int Xdim) {
    this(XmippDataJNI.new_MultidimArrayd__SWIG_2(Zdim, Ydim, Xdim), true);
  }

  public MultidimArrayd(int Ydim, int Xdim) {
    this(XmippDataJNI.new_MultidimArrayd__SWIG_3(Ydim, Xdim), true);
  }

  public MultidimArrayd(int Xdim) {
    this(XmippDataJNI.new_MultidimArrayd__SWIG_4(Xdim), true);
  }

  public MultidimArrayd(MultidimArrayd V) {
    this(XmippDataJNI.new_MultidimArrayd__SWIG_5(MultidimArrayd.getCPtr(V), V), true);
  }

  public MultidimArrayd(SWIGTYPE_p_Matrix1DT_double_t V) {
    this(XmippDataJNI.new_MultidimArrayd__SWIG_6(SWIGTYPE_p_Matrix1DT_double_t.getCPtr(V)), true);
  }

  public void clear() {
    XmippDataJNI.MultidimArrayd_clear(swigCPtr, this);
  }

  public void coreInit() {
    XmippDataJNI.MultidimArrayd_coreInit(swigCPtr, this);
  }

  public void coreAllocate(long _ndim, int _zdim, int _ydim, int _xdim) {
    XmippDataJNI.MultidimArrayd_coreAllocate__SWIG_0(swigCPtr, this, _ndim, _zdim, _ydim, _xdim);
  }

  public void coreAllocate() {
    XmippDataJNI.MultidimArrayd_coreAllocate__SWIG_1(swigCPtr, this);
  }

  public void coreAllocateReuse() {
    XmippDataJNI.MultidimArrayd_coreAllocateReuse(swigCPtr, this);
  }

  public void setMmap(boolean mmap) {
    XmippDataJNI.MultidimArrayd_setMmap(swigCPtr, this, mmap);
  }

  public void setVoxel(int k, int i, int j, double v) {
    XmippDataJNI.MultidimArrayd_setVoxel(swigCPtr, this, k, i, j, v);
  }

  public double getVoxel(int k, int i, int j) {
    return XmippDataJNI.MultidimArrayd_getVoxel(swigCPtr, this, k, i, j);
  }

  public void setDimensions(int Xdim, int Ydim, int Zdim, long Ndim) {
    XmippDataJNI.MultidimArrayd_setDimensions(swigCPtr, this, Xdim, Ydim, Zdim, Ndim);
  }

  public void setNdim(int Ndim) {
    XmippDataJNI.MultidimArrayd_setNdim(swigCPtr, this, Ndim);
  }

  public void coreDeallocate() {
    XmippDataJNI.MultidimArrayd_coreDeallocate(swigCPtr, this);
  }

  public void copyShape(MultidimArrayd m) {
    XmippDataJNI.MultidimArrayd_copyShape(swigCPtr, this, MultidimArrayd.getCPtr(m), m);
  }

  public void alias(MultidimArrayd m) {
    XmippDataJNI.MultidimArrayd_alias(swigCPtr, this, MultidimArrayd.getCPtr(m), m);
  }

  public void resize(long Ndim, int Zdim, int Ydim, int Xdim) {
    XmippDataJNI.MultidimArrayd_resize__SWIG_0(swigCPtr, this, Ndim, Zdim, Ydim, Xdim);
  }

  public void resize(int Zdim, int Ydim, int Xdim) {
    XmippDataJNI.MultidimArrayd_resize__SWIG_1(swigCPtr, this, Zdim, Ydim, Xdim);
  }

  public void resize(int Ydim, int Xdim) {
    XmippDataJNI.MultidimArrayd_resize__SWIG_2(swigCPtr, this, Ydim, Xdim);
  }

  public void resize(int Xdim) {
    XmippDataJNI.MultidimArrayd_resize__SWIG_3(swigCPtr, this, Xdim);
  }

  public void getDimensions(SWIGTYPE_p_int Xdim, SWIGTYPE_p_int Ydim, SWIGTYPE_p_int Zdim, SWIGTYPE_p_unsigned_long Ndim) {
    XmippDataJNI.MultidimArrayd_getDimensions(swigCPtr, this, SWIGTYPE_p_int.getCPtr(Xdim), SWIGTYPE_p_int.getCPtr(Ydim), SWIGTYPE_p_int.getCPtr(Zdim), SWIGTYPE_p_unsigned_long.getCPtr(Ndim));
  }

  public long getSize() {
    return XmippDataJNI.MultidimArrayd_getSize__SWIG_0(swigCPtr, this);
  }

  public int getDim() {
    return XmippDataJNI.MultidimArrayd_getDim(swigCPtr, this);
  }

  public void checkDimensionWithDebug(int dim, String file, int line) {
    XmippDataJNI.MultidimArrayd_checkDimensionWithDebug(swigCPtr, this, dim, file, line);
  }

  public void getSize(SWIGTYPE_p_int size) {
    XmippDataJNI.MultidimArrayd_getSize__SWIG_1(swigCPtr, this, SWIGTYPE_p_int.getCPtr(size));
  }

  public void window(int n0, int z0, int y0, int x0, int nF, int zF, int yF, int xF, double init_value, long n) {
    XmippDataJNI.MultidimArrayd_window__SWIG_0(swigCPtr, this, n0, z0, y0, x0, nF, zF, yF, xF, init_value, n);
  }

  public void window(int n0, int z0, int y0, int x0, int nF, int zF, int yF, int xF, double init_value) {
    XmippDataJNI.MultidimArrayd_window__SWIG_1(swigCPtr, this, n0, z0, y0, x0, nF, zF, yF, xF, init_value);
  }

  public void window(int n0, int z0, int y0, int x0, int nF, int zF, int yF, int xF) {
    XmippDataJNI.MultidimArrayd_window__SWIG_2(swigCPtr, this, n0, z0, y0, x0, nF, zF, yF, xF);
  }

  public void window(int z0, int y0, int x0, int zF, int yF, int xF, double init_value, long n) {
    XmippDataJNI.MultidimArrayd_window__SWIG_3(swigCPtr, this, z0, y0, x0, zF, yF, xF, init_value, n);
  }

  public void window(int z0, int y0, int x0, int zF, int yF, int xF, double init_value) {
    XmippDataJNI.MultidimArrayd_window__SWIG_4(swigCPtr, this, z0, y0, x0, zF, yF, xF, init_value);
  }

  public void window(int z0, int y0, int x0, int zF, int yF, int xF) {
    XmippDataJNI.MultidimArrayd_window__SWIG_5(swigCPtr, this, z0, y0, x0, zF, yF, xF);
  }

  public void window(int y0, int x0, int yF, int xF, double init_value, long n) {
    XmippDataJNI.MultidimArrayd_window__SWIG_6(swigCPtr, this, y0, x0, yF, xF, init_value, n);
  }

  public void window(int y0, int x0, int yF, int xF, double init_value) {
    XmippDataJNI.MultidimArrayd_window__SWIG_7(swigCPtr, this, y0, x0, yF, xF, init_value);
  }

  public void window(int y0, int x0, int yF, int xF) {
    XmippDataJNI.MultidimArrayd_window__SWIG_8(swigCPtr, this, y0, x0, yF, xF);
  }

  public void window(int x0, int xF, double init_value, long n) {
    XmippDataJNI.MultidimArrayd_window__SWIG_9(swigCPtr, this, x0, xF, init_value, n);
  }

  public void window(int x0, int xF, double init_value) {
    XmippDataJNI.MultidimArrayd_window__SWIG_10(swigCPtr, this, x0, xF, init_value);
  }

  public void window(int x0, int xF) {
    XmippDataJNI.MultidimArrayd_window__SWIG_11(swigCPtr, this, x0, xF);
  }

  public void printShape(SWIGTYPE_p_std__ostream out) {
    XmippDataJNI.MultidimArrayd_printShape__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out));
  }

  public void printShape() {
    XmippDataJNI.MultidimArrayd_printShape__SWIG_1(swigCPtr, this);
  }

  public boolean outside(int k, int i, int j) {
    return XmippDataJNI.MultidimArrayd_outside__SWIG_0(swigCPtr, this, k, i, j);
  }

  public boolean outside(int i, int j) {
    return XmippDataJNI.MultidimArrayd_outside__SWIG_1(swigCPtr, this, i, j);
  }

  public boolean outside(int i) {
    return XmippDataJNI.MultidimArrayd_outside__SWIG_2(swigCPtr, this, i);
  }

  public boolean outside(SWIGTYPE_p_Matrix1DT_double_t r) {
    return XmippDataJNI.MultidimArrayd_outside__SWIG_3(swigCPtr, this, SWIGTYPE_p_Matrix1DT_double_t.getCPtr(r));
  }

  public void getImage(long n, MultidimArrayd M) {
    XmippDataJNI.MultidimArrayd_getImage(swigCPtr, this, n, MultidimArrayd.getCPtr(M), M);
  }

  public void getSlice(int k, MultidimArrayd M, char axis, long n) {
    XmippDataJNI.MultidimArrayd_getSlice__SWIG_0(swigCPtr, this, k, MultidimArrayd.getCPtr(M), M, axis, n);
  }

  public void getSlice(int k, MultidimArrayd M, char axis) {
    XmippDataJNI.MultidimArrayd_getSlice__SWIG_1(swigCPtr, this, k, MultidimArrayd.getCPtr(M), M, axis);
  }

  public void getSlice(int k, MultidimArrayd M) {
    XmippDataJNI.MultidimArrayd_getSlice__SWIG_2(swigCPtr, this, k, MultidimArrayd.getCPtr(M), M);
  }

  public void setSlice(int k, MultidimArrayd v, long n) {
    XmippDataJNI.MultidimArrayd_setSlice__SWIG_0(swigCPtr, this, k, MultidimArrayd.getCPtr(v), v, n);
  }

  public void setSlice(int k, MultidimArrayd v) {
    XmippDataJNI.MultidimArrayd_setSlice__SWIG_1(swigCPtr, this, k, MultidimArrayd.getCPtr(v), v);
  }

  public int rowNumber() {
    return XmippDataJNI.MultidimArrayd_rowNumber(swigCPtr, this);
  }

  public int colNumber() {
    return XmippDataJNI.MultidimArrayd_colNumber(swigCPtr, this);
  }

  public void getCol(int j, MultidimArrayd v) {
    XmippDataJNI.MultidimArrayd_getCol(swigCPtr, this, j, MultidimArrayd.getCPtr(v), v);
  }

  public void setCol(int j, MultidimArrayd v) {
    XmippDataJNI.MultidimArrayd_setCol(swigCPtr, this, j, MultidimArrayd.getCPtr(v), v);
  }

  public void getRow(int i, MultidimArrayd v) {
    XmippDataJNI.MultidimArrayd_getRow(swigCPtr, this, i, MultidimArrayd.getCPtr(v), v);
  }

  public void setRow(int i, MultidimArrayd v) {
    XmippDataJNI.MultidimArrayd_setRow(swigCPtr, this, i, MultidimArrayd.getCPtr(v), v);
  }

  public void toPhysical(int k_log, int i_log, int j_log, SWIGTYPE_p_int k_phys, SWIGTYPE_p_int i_phys, SWIGTYPE_p_int j_phys) {
    XmippDataJNI.MultidimArrayd_toPhysical__SWIG_0(swigCPtr, this, k_log, i_log, j_log, SWIGTYPE_p_int.getCPtr(k_phys), SWIGTYPE_p_int.getCPtr(i_phys), SWIGTYPE_p_int.getCPtr(j_phys));
  }

  public void toLogical(int k_phys, int i_phys, int j_phys, SWIGTYPE_p_int k_log, SWIGTYPE_p_int i_log, SWIGTYPE_p_int j_log) {
    XmippDataJNI.MultidimArrayd_toLogical__SWIG_0(swigCPtr, this, k_phys, i_phys, j_phys, SWIGTYPE_p_int.getCPtr(k_log), SWIGTYPE_p_int.getCPtr(i_log), SWIGTYPE_p_int.getCPtr(j_log));
  }

  public void toPhysical(int i_log, int j_log, SWIGTYPE_p_int i_phys, SWIGTYPE_p_int j_phys) {
    XmippDataJNI.MultidimArrayd_toPhysical__SWIG_1(swigCPtr, this, i_log, j_log, SWIGTYPE_p_int.getCPtr(i_phys), SWIGTYPE_p_int.getCPtr(j_phys));
  }

  public void toLogical(int i_phys, int j_phys, SWIGTYPE_p_int i_log, SWIGTYPE_p_int j_log) {
    XmippDataJNI.MultidimArrayd_toLogical__SWIG_1(swigCPtr, this, i_phys, j_phys, SWIGTYPE_p_int.getCPtr(i_log), SWIGTYPE_p_int.getCPtr(j_log));
  }

  public void toPhysical(int i_log, SWIGTYPE_p_int i_phys) {
    XmippDataJNI.MultidimArrayd_toPhysical__SWIG_2(swigCPtr, this, i_log, SWIGTYPE_p_int.getCPtr(i_phys));
  }

  public void toLogical(int i_phys, SWIGTYPE_p_int i_log) {
    XmippDataJNI.MultidimArrayd_toLogical__SWIG_2(swigCPtr, this, i_phys, SWIGTYPE_p_int.getCPtr(i_log));
  }

  public double interpolatedElement3D(double x, double y, double z, double outside_value, int n) {
    return XmippDataJNI.MultidimArrayd_interpolatedElement3D__SWIG_0(swigCPtr, this, x, y, z, outside_value, n);
  }

  public double interpolatedElement3D(double x, double y, double z, double outside_value) {
    return XmippDataJNI.MultidimArrayd_interpolatedElement3D__SWIG_1(swigCPtr, this, x, y, z, outside_value);
  }

  public double interpolatedElement3D(double x, double y, double z) {
    return XmippDataJNI.MultidimArrayd_interpolatedElement3D__SWIG_2(swigCPtr, this, x, y, z);
  }

  public double interpolatedElement2D(double x, double y, double outside_value, int n) {
    return XmippDataJNI.MultidimArrayd_interpolatedElement2D__SWIG_0(swigCPtr, this, x, y, outside_value, n);
  }

  public double interpolatedElement2D(double x, double y, double outside_value) {
    return XmippDataJNI.MultidimArrayd_interpolatedElement2D__SWIG_1(swigCPtr, this, x, y, outside_value);
  }

  public double interpolatedElement2D(double x, double y) {
    return XmippDataJNI.MultidimArrayd_interpolatedElement2D__SWIG_2(swigCPtr, this, x, y);
  }

  public double interpolatedElementBSpline3D(double x, double y, double z, int SplineDegree, long n) {
    return XmippDataJNI.MultidimArrayd_interpolatedElementBSpline3D__SWIG_0(swigCPtr, this, x, y, z, SplineDegree, n);
  }

  public double interpolatedElementBSpline3D(double x, double y, double z, int SplineDegree) {
    return XmippDataJNI.MultidimArrayd_interpolatedElementBSpline3D__SWIG_1(swigCPtr, this, x, y, z, SplineDegree);
  }

  public double interpolatedElementBSpline3D(double x, double y, double z) {
    return XmippDataJNI.MultidimArrayd_interpolatedElementBSpline3D__SWIG_2(swigCPtr, this, x, y, z);
  }

  public double interpolatedElementBSpline2D(double x, double y, int SplineDegree, long n) {
    return XmippDataJNI.MultidimArrayd_interpolatedElementBSpline2D__SWIG_0(swigCPtr, this, x, y, SplineDegree, n);
  }

  public double interpolatedElementBSpline2D(double x, double y, int SplineDegree) {
    return XmippDataJNI.MultidimArrayd_interpolatedElementBSpline2D__SWIG_1(swigCPtr, this, x, y, SplineDegree);
  }

  public double interpolatedElementBSpline2D(double x, double y) {
    return XmippDataJNI.MultidimArrayd_interpolatedElementBSpline2D__SWIG_2(swigCPtr, this, x, y);
  }

  public double interpolatedElementBSpline1D(double x, int SplineDegree, long n) {
    return XmippDataJNI.MultidimArrayd_interpolatedElementBSpline1D__SWIG_0(swigCPtr, this, x, SplineDegree, n);
  }

  public double interpolatedElementBSpline1D(double x, int SplineDegree) {
    return XmippDataJNI.MultidimArrayd_interpolatedElementBSpline1D__SWIG_1(swigCPtr, this, x, SplineDegree);
  }

  public double interpolatedElementBSpline1D(double x) {
    return XmippDataJNI.MultidimArrayd_interpolatedElementBSpline1D__SWIG_2(swigCPtr, this, x);
  }

  public void setXmippOrigin() {
    XmippDataJNI.MultidimArrayd_setXmippOrigin(swigCPtr, this);
  }

  public void moveOriginTo(int k, int i, int j) {
    XmippDataJNI.MultidimArrayd_moveOriginTo__SWIG_0(swigCPtr, this, k, i, j);
  }

  public void moveOriginTo(int i, int j) {
    XmippDataJNI.MultidimArrayd_moveOriginTo__SWIG_1(swigCPtr, this, i, j);
  }

  public int startingZ() {
    return XmippDataJNI.MultidimArrayd_startingZ(swigCPtr, this);
  }

  public int finishingZ() {
    return XmippDataJNI.MultidimArrayd_finishingZ(swigCPtr, this);
  }

  public int startingY() {
    return XmippDataJNI.MultidimArrayd_startingY(swigCPtr, this);
  }

  public int finishingY() {
    return XmippDataJNI.MultidimArrayd_finishingY(swigCPtr, this);
  }

  public int startingX() {
    return XmippDataJNI.MultidimArrayd_startingX(swigCPtr, this);
  }

  public int finishingX() {
    return XmippDataJNI.MultidimArrayd_finishingX(swigCPtr, this);
  }

  public SWIGTYPE_p_p_p_double adaptForNumericalRecipes3D(long n) {
    long cPtr = XmippDataJNI.MultidimArrayd_adaptForNumericalRecipes3D__SWIG_0(swigCPtr, this, n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_p_double(cPtr, false);
  }

  public SWIGTYPE_p_p_p_double adaptForNumericalRecipes3D() {
    long cPtr = XmippDataJNI.MultidimArrayd_adaptForNumericalRecipes3D__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_p_double(cPtr, false);
  }

  public void killAdaptationForNumericalRecipes3D(SWIGTYPE_p_p_p_double m) {
    XmippDataJNI.MultidimArrayd_killAdaptationForNumericalRecipes3D(swigCPtr, this, SWIGTYPE_p_p_p_double.getCPtr(m));
  }

  public SWIGTYPE_p_p_double adaptForNumericalRecipes2D(long n) {
    long cPtr = XmippDataJNI.MultidimArrayd_adaptForNumericalRecipes2D__SWIG_0(swigCPtr, this, n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_double(cPtr, false);
  }

  public SWIGTYPE_p_p_double adaptForNumericalRecipes2D() {
    long cPtr = XmippDataJNI.MultidimArrayd_adaptForNumericalRecipes2D__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_double(cPtr, false);
  }

  public SWIGTYPE_p_double adaptForNumericalRecipes22D() {
    long cPtr = XmippDataJNI.MultidimArrayd_adaptForNumericalRecipes22D(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void loadFromNumericalRecipes2D(SWIGTYPE_p_p_double m, int Ydim, int Xdim) {
    XmippDataJNI.MultidimArrayd_loadFromNumericalRecipes2D(swigCPtr, this, SWIGTYPE_p_p_double.getCPtr(m), Ydim, Xdim);
  }

  public void killAdaptationForNumericalRecipes2D(SWIGTYPE_p_p_double m) {
    XmippDataJNI.MultidimArrayd_killAdaptationForNumericalRecipes2D(swigCPtr, this, SWIGTYPE_p_p_double.getCPtr(m));
  }

  public void killAdaptationForNumericalRecipes22D(SWIGTYPE_p_p_double m) {
    XmippDataJNI.MultidimArrayd_killAdaptationForNumericalRecipes22D(swigCPtr, this, SWIGTYPE_p_p_double.getCPtr(m));
  }

  public SWIGTYPE_p_double adaptForNumericalRecipes1D() {
    long cPtr = XmippDataJNI.MultidimArrayd_adaptForNumericalRecipes1D(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void killAdaptationForNumericalRecipes1D(SWIGTYPE_p_double m) {
    XmippDataJNI.MultidimArrayd_killAdaptationForNumericalRecipes1D(swigCPtr, this, SWIGTYPE_p_double.getCPtr(m));
  }

  public void printStats(SWIGTYPE_p_std__ostream out) {
    XmippDataJNI.MultidimArrayd_printStats__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(out));
  }

  public void printStats() {
    XmippDataJNI.MultidimArrayd_printStats__SWIG_1(swigCPtr, this);
  }

  public double computeMax() {
    return XmippDataJNI.MultidimArrayd_computeMax(swigCPtr, this);
  }

  public double computeMin() {
    return XmippDataJNI.MultidimArrayd_computeMin(swigCPtr, this);
  }

  public void minIndex(SWIGTYPE_p_int lmin, SWIGTYPE_p_int kmin, SWIGTYPE_p_int imin, SWIGTYPE_p_int jmin) {
    XmippDataJNI.MultidimArrayd_minIndex__SWIG_0(swigCPtr, this, SWIGTYPE_p_int.getCPtr(lmin), SWIGTYPE_p_int.getCPtr(kmin), SWIGTYPE_p_int.getCPtr(imin), SWIGTYPE_p_int.getCPtr(jmin));
  }

  public void minIndex(SWIGTYPE_p_int kmin, SWIGTYPE_p_int imin, SWIGTYPE_p_int jmin) {
    XmippDataJNI.MultidimArrayd_minIndex__SWIG_1(swigCPtr, this, SWIGTYPE_p_int.getCPtr(kmin), SWIGTYPE_p_int.getCPtr(imin), SWIGTYPE_p_int.getCPtr(jmin));
  }

  public void minIndex(SWIGTYPE_p_int imin, SWIGTYPE_p_int jmin) {
    XmippDataJNI.MultidimArrayd_minIndex__SWIG_2(swigCPtr, this, SWIGTYPE_p_int.getCPtr(imin), SWIGTYPE_p_int.getCPtr(jmin));
  }

  public void minIndex(SWIGTYPE_p_int jmin) {
    XmippDataJNI.MultidimArrayd_minIndex__SWIG_3(swigCPtr, this, SWIGTYPE_p_int.getCPtr(jmin));
  }

  public void maxIndex(SWIGTYPE_p_int lmax, SWIGTYPE_p_int kmax, SWIGTYPE_p_int imax, SWIGTYPE_p_int jmax) {
    XmippDataJNI.MultidimArrayd_maxIndex__SWIG_0(swigCPtr, this, SWIGTYPE_p_int.getCPtr(lmax), SWIGTYPE_p_int.getCPtr(kmax), SWIGTYPE_p_int.getCPtr(imax), SWIGTYPE_p_int.getCPtr(jmax));
  }

  public void maxIndex(SWIGTYPE_p_int kmax, SWIGTYPE_p_int imax, SWIGTYPE_p_int jmax) {
    XmippDataJNI.MultidimArrayd_maxIndex__SWIG_1(swigCPtr, this, SWIGTYPE_p_int.getCPtr(kmax), SWIGTYPE_p_int.getCPtr(imax), SWIGTYPE_p_int.getCPtr(jmax));
  }

  public void maxIndex(SWIGTYPE_p_int imax, SWIGTYPE_p_int jmax) {
    XmippDataJNI.MultidimArrayd_maxIndex__SWIG_2(swigCPtr, this, SWIGTYPE_p_int.getCPtr(imax), SWIGTYPE_p_int.getCPtr(jmax));
  }

  public void maxIndex(SWIGTYPE_p_int jmax) {
    XmippDataJNI.MultidimArrayd_maxIndex__SWIG_3(swigCPtr, this, SWIGTYPE_p_int.getCPtr(jmax));
  }

  public void computeDoubleMinMax(SWIGTYPE_p_double minval, SWIGTYPE_p_double maxval) {
    XmippDataJNI.MultidimArrayd_computeDoubleMinMax(swigCPtr, this, SWIGTYPE_p_double.getCPtr(minval), SWIGTYPE_p_double.getCPtr(maxval));
  }

  public double computeAvg() {
    return XmippDataJNI.MultidimArrayd_computeAvg(swigCPtr, this);
  }

  public double computeStddev() {
    return XmippDataJNI.MultidimArrayd_computeStddev(swigCPtr, this);
  }

  public void computeStats(SWIGTYPE_p_double avg, SWIGTYPE_p_double stddev, SWIGTYPE_p_double minval, SWIGTYPE_p_double maxval) {
    XmippDataJNI.MultidimArrayd_computeStats__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(avg), SWIGTYPE_p_double.getCPtr(stddev), SWIGTYPE_p_double.getCPtr(minval), SWIGTYPE_p_double.getCPtr(maxval));
  }

  public void computeStats(SWIGTYPE_p_double avg, SWIGTYPE_p_double stddev, SWIGTYPE_p_double min_val, SWIGTYPE_p_double max_val, SWIGTYPE_p_Matrix1DT_int_t corner1, SWIGTYPE_p_Matrix1DT_int_t corner2, long n) {
    XmippDataJNI.MultidimArrayd_computeStats__SWIG_1(swigCPtr, this, SWIGTYPE_p_double.getCPtr(avg), SWIGTYPE_p_double.getCPtr(stddev), SWIGTYPE_p_double.getCPtr(min_val), SWIGTYPE_p_double.getCPtr(max_val), SWIGTYPE_p_Matrix1DT_int_t.getCPtr(corner1), SWIGTYPE_p_Matrix1DT_int_t.getCPtr(corner2), n);
  }

  public void computeStats(SWIGTYPE_p_double avg, SWIGTYPE_p_double stddev, SWIGTYPE_p_double min_val, SWIGTYPE_p_double max_val, SWIGTYPE_p_Matrix1DT_int_t corner1, SWIGTYPE_p_Matrix1DT_int_t corner2) {
    XmippDataJNI.MultidimArrayd_computeStats__SWIG_2(swigCPtr, this, SWIGTYPE_p_double.getCPtr(avg), SWIGTYPE_p_double.getCPtr(stddev), SWIGTYPE_p_double.getCPtr(min_val), SWIGTYPE_p_double.getCPtr(max_val), SWIGTYPE_p_Matrix1DT_int_t.getCPtr(corner1), SWIGTYPE_p_Matrix1DT_int_t.getCPtr(corner2));
  }

  public boolean isCorner(SWIGTYPE_p_Matrix1DT_double_t v) {
    return XmippDataJNI.MultidimArrayd_isCorner(swigCPtr, this, SWIGTYPE_p_Matrix1DT_double_t.getCPtr(v));
  }

  public double computeMedian() {
    return XmippDataJNI.MultidimArrayd_computeMedian(swigCPtr, this);
  }

  public void rangeAdjust(double minF, double maxF) {
    XmippDataJNI.MultidimArrayd_rangeAdjust__SWIG_0(swigCPtr, this, minF, maxF);
  }

  public void rangeAdjust(double minF, double maxF, SWIGTYPE_p_MultidimArrayT_int_t mask) {
    XmippDataJNI.MultidimArrayd_rangeAdjust__SWIG_1(swigCPtr, this, minF, maxF, SWIGTYPE_p_MultidimArrayT_int_t.getCPtr(mask));
  }

  public void rangeAdjust(MultidimArrayd example, SWIGTYPE_p_MultidimArrayT_int_t mask) {
    XmippDataJNI.MultidimArrayd_rangeAdjust__SWIG_2(swigCPtr, this, MultidimArrayd.getCPtr(example), example, SWIGTYPE_p_MultidimArrayT_int_t.getCPtr(mask));
  }

  public void rangeAdjust(MultidimArrayd example) {
    XmippDataJNI.MultidimArrayd_rangeAdjust__SWIG_3(swigCPtr, this, MultidimArrayd.getCPtr(example), example);
  }

  public void statisticsAdjust(double avgF, double stddevF) {
    XmippDataJNI.MultidimArrayd_statisticsAdjust(swigCPtr, this, avgF, stddevF);
  }

  public MultidimArrayd add(MultidimArrayd op1) {
    return new MultidimArrayd(XmippDataJNI.MultidimArrayd_add__SWIG_0(swigCPtr, this, MultidimArrayd.getCPtr(op1), op1), true);
  }

  public MultidimArrayd sub(MultidimArrayd op1) {
    return new MultidimArrayd(XmippDataJNI.MultidimArrayd_sub__SWIG_0(swigCPtr, this, MultidimArrayd.getCPtr(op1), op1), true);
  }

  public MultidimArrayd mul(MultidimArrayd op1) {
    return new MultidimArrayd(XmippDataJNI.MultidimArrayd_mul__SWIG_0(swigCPtr, this, MultidimArrayd.getCPtr(op1), op1), true);
  }

  public MultidimArrayd div(MultidimArrayd op1) {
    return new MultidimArrayd(XmippDataJNI.MultidimArrayd_div__SWIG_0(swigCPtr, this, MultidimArrayd.getCPtr(op1), op1), true);
  }

  public MultidimArrayd add(double op1) {
    return new MultidimArrayd(XmippDataJNI.MultidimArrayd_add__SWIG_1(swigCPtr, this, op1), true);
  }

  public MultidimArrayd sub(double op1) {
    return new MultidimArrayd(XmippDataJNI.MultidimArrayd_sub__SWIG_1(swigCPtr, this, op1), true);
  }

  public MultidimArrayd mul(double op1) {
    return new MultidimArrayd(XmippDataJNI.MultidimArrayd_mul__SWIG_1(swigCPtr, this, op1), true);
  }

  public MultidimArrayd div(double op1) {
    return new MultidimArrayd(XmippDataJNI.MultidimArrayd_div__SWIG_1(swigCPtr, this, op1), true);
  }

  public void initConstant(double val) {
    XmippDataJNI.MultidimArrayd_initConstant(swigCPtr, this, val);
  }

  public void initZeros() {
    XmippDataJNI.MultidimArrayd_initZeros__SWIG_1(swigCPtr, this);
  }

  public void initZeros(long Ndim, int Zdim, int Ydim, int Xdim) {
    XmippDataJNI.MultidimArrayd_initZeros__SWIG_2(swigCPtr, this, Ndim, Zdim, Ydim, Xdim);
  }

  public void initZeros(int Xdim) {
    XmippDataJNI.MultidimArrayd_initZeros__SWIG_3(swigCPtr, this, Xdim);
  }

  public void initZeros(int Ydim, int Xdim) {
    XmippDataJNI.MultidimArrayd_initZeros__SWIG_4(swigCPtr, this, Ydim, Xdim);
  }

  public void initZeros(int Zdim, int Ydim, int Xdim) {
    XmippDataJNI.MultidimArrayd_initZeros__SWIG_5(swigCPtr, this, Zdim, Ydim, Xdim);
  }

  public void initLinear(double minF, double maxF, int n, String mode) {
    XmippDataJNI.MultidimArrayd_initLinear__SWIG_0(swigCPtr, this, minF, maxF, n, mode);
  }

  public void initLinear(double minF, double maxF, int n) {
    XmippDataJNI.MultidimArrayd_initLinear__SWIG_1(swigCPtr, this, minF, maxF, n);
  }

  public void initLinear(double minF, double maxF) {
    XmippDataJNI.MultidimArrayd_initLinear__SWIG_2(swigCPtr, this, minF, maxF);
  }

  public void initRandom(double op1, double op2, String mode) {
    XmippDataJNI.MultidimArrayd_initRandom__SWIG_0(swigCPtr, this, op1, op2, mode);
  }

  public void initRandom(double op1, double op2) {
    XmippDataJNI.MultidimArrayd_initRandom__SWIG_1(swigCPtr, this, op1, op2);
  }

  public void addNoise(double op1, double op2, String mode, double df) {
    XmippDataJNI.MultidimArrayd_addNoise__SWIG_0(swigCPtr, this, op1, op2, mode, df);
  }

  public void addNoise(double op1, double op2, String mode) {
    XmippDataJNI.MultidimArrayd_addNoise__SWIG_1(swigCPtr, this, op1, op2, mode);
  }

  public void addNoise(double op1, double op2) {
    XmippDataJNI.MultidimArrayd_addNoise__SWIG_2(swigCPtr, this, op1, op2);
  }

  public void centerOfMass(SWIGTYPE_p_Matrix1DT_double_t center, SWIGTYPE_p_void mask, long n) {
    XmippDataJNI.MultidimArrayd_centerOfMass__SWIG_0(swigCPtr, this, SWIGTYPE_p_Matrix1DT_double_t.getCPtr(center), SWIGTYPE_p_void.getCPtr(mask), n);
  }

  public void centerOfMass(SWIGTYPE_p_Matrix1DT_double_t center, SWIGTYPE_p_void mask) {
    XmippDataJNI.MultidimArrayd_centerOfMass__SWIG_1(swigCPtr, this, SWIGTYPE_p_Matrix1DT_double_t.getCPtr(center), SWIGTYPE_p_void.getCPtr(mask));
  }

  public void centerOfMass(SWIGTYPE_p_Matrix1DT_double_t center) {
    XmippDataJNI.MultidimArrayd_centerOfMass__SWIG_2(swigCPtr, this, SWIGTYPE_p_Matrix1DT_double_t.getCPtr(center));
  }

  public MultidimArrayd sort() {
    return new MultidimArrayd(XmippDataJNI.MultidimArrayd_sort(swigCPtr, this), true);
  }

  public SWIGTYPE_p_MultidimArrayT_int_t indexSort() {
    return new SWIGTYPE_p_MultidimArrayT_int_t(XmippDataJNI.MultidimArrayd_indexSort(swigCPtr, this), true);
  }

  public void threshold(String type, double a, double b, SWIGTYPE_p_MultidimArrayT_int_t mask) {
    XmippDataJNI.MultidimArrayd_threshold__SWIG_0(swigCPtr, this, type, a, b, SWIGTYPE_p_MultidimArrayT_int_t.getCPtr(mask));
  }

  public void threshold(String type, double a, double b) {
    XmippDataJNI.MultidimArrayd_threshold__SWIG_1(swigCPtr, this, type, a, b);
  }

  public long countThreshold(String type, double a, double b, SWIGTYPE_p_MultidimArrayT_int_t mask) {
    return XmippDataJNI.MultidimArrayd_countThreshold__SWIG_0(swigCPtr, this, type, a, b, SWIGTYPE_p_MultidimArrayT_int_t.getCPtr(mask));
  }

  public long countThreshold(String type, double a, double b) {
    return XmippDataJNI.MultidimArrayd_countThreshold__SWIG_1(swigCPtr, this, type, a, b);
  }

  public void substitute(double oldv, double newv, double accuracy, SWIGTYPE_p_MultidimArrayT_int_t mask) {
    XmippDataJNI.MultidimArrayd_substitute__SWIG_0(swigCPtr, this, oldv, newv, accuracy, SWIGTYPE_p_MultidimArrayT_int_t.getCPtr(mask));
  }

  public void substitute(double oldv, double newv, double accuracy) {
    XmippDataJNI.MultidimArrayd_substitute__SWIG_1(swigCPtr, this, oldv, newv, accuracy);
  }

  public void substitute(double oldv, double newv) {
    XmippDataJNI.MultidimArrayd_substitute__SWIG_2(swigCPtr, this, oldv, newv);
  }

  public void randomSubstitute(double oldv, double avgv, double sigv, double accuracy, SWIGTYPE_p_MultidimArrayT_int_t mask) {
    XmippDataJNI.MultidimArrayd_randomSubstitute__SWIG_0(swigCPtr, this, oldv, avgv, sigv, accuracy, SWIGTYPE_p_MultidimArrayT_int_t.getCPtr(mask));
  }

  public void randomSubstitute(double oldv, double avgv, double sigv, double accuracy) {
    XmippDataJNI.MultidimArrayd_randomSubstitute__SWIG_1(swigCPtr, this, oldv, avgv, sigv, accuracy);
  }

  public void randomSubstitute(double oldv, double avgv, double sigv) {
    XmippDataJNI.MultidimArrayd_randomSubstitute__SWIG_2(swigCPtr, this, oldv, avgv, sigv);
  }

  public void binarize(double val, double accuracy, SWIGTYPE_p_MultidimArrayT_int_t mask) {
    XmippDataJNI.MultidimArrayd_binarize__SWIG_0(swigCPtr, this, val, accuracy, SWIGTYPE_p_MultidimArrayT_int_t.getCPtr(mask));
  }

  public void binarize(double val, double accuracy) {
    XmippDataJNI.MultidimArrayd_binarize__SWIG_1(swigCPtr, this, val, accuracy);
  }

  public void binarize(double val) {
    XmippDataJNI.MultidimArrayd_binarize__SWIG_2(swigCPtr, this, val);
  }

  public void binarize() {
    XmippDataJNI.MultidimArrayd_binarize__SWIG_3(swigCPtr, this);
  }

  public void selfROUND() {
    XmippDataJNI.MultidimArrayd_selfROUND(swigCPtr, this);
  }

  public void selfCEIL() {
    XmippDataJNI.MultidimArrayd_selfCEIL(swigCPtr, this);
  }

  public void selfFLOOR() {
    XmippDataJNI.MultidimArrayd_selfFLOOR(swigCPtr, this);
  }

  public void selfABS() {
    XmippDataJNI.MultidimArrayd_selfABS(swigCPtr, this);
  }

  public void selfSQRT() {
    XmippDataJNI.MultidimArrayd_selfSQRT(swigCPtr, this);
  }

  public double sum() {
    return XmippDataJNI.MultidimArrayd_sum(swigCPtr, this);
  }

  public double sum2() {
    return XmippDataJNI.MultidimArrayd_sum2(swigCPtr, this);
  }

  public void selfLog10() {
    XmippDataJNI.MultidimArrayd_selfLog10(swigCPtr, this);
  }

  public void selfReverseX() {
    XmippDataJNI.MultidimArrayd_selfReverseX(swigCPtr, this);
  }

  public void selfReverseY() {
    XmippDataJNI.MultidimArrayd_selfReverseY(swigCPtr, this);
  }

  public void selfReverseZ() {
    XmippDataJNI.MultidimArrayd_selfReverseZ(swigCPtr, this);
  }

  public MultidimArrayd sub() {
    return new MultidimArrayd(XmippDataJNI.MultidimArrayd_sub__SWIG_2(swigCPtr, this), true);
  }

  public boolean equal(MultidimArrayd op, double accuracy) {
    return XmippDataJNI.MultidimArrayd_equal__SWIG_0(swigCPtr, this, MultidimArrayd.getCPtr(op), op, accuracy);
  }

  public boolean equal(MultidimArrayd op) {
    return XmippDataJNI.MultidimArrayd_equal__SWIG_1(swigCPtr, this, MultidimArrayd.getCPtr(op), op);
  }

  public void profile(int x0, int y0, int xF, int yF, int N, MultidimArrayd profile) {
    XmippDataJNI.MultidimArrayd_profile(swigCPtr, this, x0, y0, xF, yF, N, MultidimArrayd.getCPtr(profile), profile);
  }

  public void showWithGnuPlot(String xlabel, String title) {
    XmippDataJNI.MultidimArrayd_showWithGnuPlot(swigCPtr, this, xlabel, title);
  }

  public void edit() {
    XmippDataJNI.MultidimArrayd_edit(swigCPtr, this);
  }

  public void write(FileName fn) {
    XmippDataJNI.MultidimArrayd_write(swigCPtr, this, FileName.getCPtr(fn), fn);
  }

}
