/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class Projection extends ImageDouble {

    protected Projection(long cPtr, boolean cMemoryOwn) {
        super(XmippDataJNI.SWIGProjectionUpcast(cPtr), cMemoryOwn);
        swigCPtr = cPtr;
    }

    protected static long getCPtr(Projection obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                XmippDataJNI.delete_Projection(swigCPtr);
            }
            swigCPtr = 0;
        }
        super.delete();
    }

    public Projection() {
        this(XmippDataJNI.new_Projection(), true);
    }

    public void setDirection(SWIGTYPE_p_Matrix1DT_double_t value) {
        XmippDataJNI.Projection_direction_set(swigCPtr, this, SWIGTYPE_p_Matrix1DT_double_t.getCPtr(value));
    }

    public SWIGTYPE_p_Matrix1DT_double_t getDirection() {
        return new SWIGTYPE_p_Matrix1DT_double_t(XmippDataJNI.Projection_direction_get(swigCPtr, this), true);
    }

    public void setEuler(SWIGTYPE_p_Matrix2DT_double_t value) {
        XmippDataJNI.Projection_euler_set(swigCPtr, this, SWIGTYPE_p_Matrix2DT_double_t.getCPtr(value));
    }

    public SWIGTYPE_p_Matrix2DT_double_t getEuler() {
        return new SWIGTYPE_p_Matrix2DT_double_t(XmippDataJNI.Projection_euler_get(swigCPtr, this), true);
    }

    public void setEulert(SWIGTYPE_p_Matrix2DT_double_t value) {
        XmippDataJNI.Projection_eulert_set(swigCPtr, this, SWIGTYPE_p_Matrix2DT_double_t.getCPtr(value));
    }

    public SWIGTYPE_p_Matrix2DT_double_t getEulert() {
        return new SWIGTYPE_p_Matrix2DT_double_t(XmippDataJNI.Projection_eulert_get(swigCPtr, this), true);
    }

    public void reset(int Ydim, int Xdim) {
        XmippDataJNI.Projection_reset(swigCPtr, this, Ydim, Xdim);
    }

    public void set_angles(double _rot, double _tilt, double _psi) {
        XmippDataJNI.Projection_set_angles(swigCPtr, this, _rot, _tilt, _psi);
    }

    public void assign(Projection P) {
        XmippDataJNI.Projection_assign(swigCPtr, this, Projection.getCPtr(P), P);
    }
}
