/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class xmippBaseListener {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected xmippBaseListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(xmippBaseListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XmippDataJNI.delete_xmippBaseListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void OnInitOperation(long _est_it) {
    XmippDataJNI.xmippBaseListener_OnInitOperation(swigCPtr, this, _est_it);
  }

  public void OnReportOperation(String _rsOp) {
    XmippDataJNI.xmippBaseListener_OnReportOperation(swigCPtr, this, _rsOp);
  }

  public void OnProgress(long _it) {
    XmippDataJNI.xmippBaseListener_OnProgress(swigCPtr, this, _it);
  }

  public long getVerbosity() {
    return XmippDataJNI.xmippBaseListener_getVerbosity(swigCPtr, this);
  }

  public SWIGTYPE_p_unsigned_int setVerbosity() {
    return new SWIGTYPE_p_unsigned_int(XmippDataJNI.xmippBaseListener_setVerbosity(swigCPtr, this), false);
  }

  public boolean OnUserCancel() {
    return XmippDataJNI.xmippBaseListener_OnUserCancel(swigCPtr, this);
  }

  public SWIGTYPE_p_bool setCancel() {
    return new SWIGTYPE_p_bool(XmippDataJNI.xmippBaseListener_setCancel(swigCPtr, this), false);
  }

}
