/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FileListRenderer.java
 *
 * Created on 18-ene-2010, 11:31:30
 */
package browser.files;

import browser.imageitems.listitems.FileItem;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Juanjo Vega
 */
public class FileListRenderer extends JPanel implements ListCellRenderer {

    /** Creates new form FileListRenderer */
    public FileListRenderer() {
        super();

        initComponents();
    }

    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        FileItem file = (FileItem) value;

        jlItem.setIcon(file.getIcon());

        jlItem.setText("<html>" + file.getLabel() + "<br><i><small>"
                + (index > 0 ? file.getDescription() : " ") + "</small></i></html>");

        if (isSelected) {
            setBackground(list.getSelectionBackground());
            setForeground(list.getSelectionForeground());
        } else {
            setBackground(list.getBackground());
            setForeground(list.getForeground());
        }

//        repaint(); // Update icon

        return this;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlItem = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());
        add(jlItem, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlItem;
    // End of variables declaration//GEN-END:variables
}
